### ISSUE TITLE
NPE in addParticipantVideo

### ISSUE THREAD

**Issue by PingForward** [twilio/video-quickstart-android#151]
### Description

If I answer the call and immediately minimize the app `onPause ` will be called before second participant will connect to room and then participantListener will be triggered and NPE will be thrown because localVideoTrack was set to null in onPause

### Steps to Reproduce

1. Open room as second partisipant
2. Immediately minimize the app (before first participant connected 0.5s)

#### Code

**So, what do we have?**
onPause method
```
  if (localVideoTrack != null) {
            /*
             * If this local video track is being shared in a Room, remove from local
             * participant before releasing the video track. Participants will be notified that
             * the track has been removed.
             */
            if (localParticipant != null) {
                localParticipant.removeVideoTrack(localVideoTrack);
            }

            localVideoTrack.release();
            localVideoTrack = null;
        }
```
  **localVideoTrack = null;**

Then in the background second participant connected to the room and  `private Participant.Listener participantListener()` will be triggered

```
  @Override
            public void onVideoTrackAdded(Participant participant, VideoTrack videoTrack) {
                addParticipantVideo(videoTrack);
            }
```
moveLocalVideoToThumbnailView called from addParticipantVideo
  ```
 private void moveLocalVideoToThumbnailView() {
        if (thumbnailVideoView != null && thumbnailVideoView.getVisibility() == View.GONE) {
            thumbnailVideoView.setVisibility(View.VISIBLE);
            **localVideoTrack.removeRenderer(primaryVideoView);
            localVideoTrack.addRenderer(thumbnailVideoView);**
            localVideoView = thumbnailVideoView;
            thumbnailVideoView.setMirror(cameraCapturerCompat.getCameraSource() ==
                    CameraSource.FRONT_CAMERA);
        }
    }
```
**We have NPE because localVideoTrack was set to null in onPause**

#### Logs

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.twilio.video.LocalVideoTrack.removeRenderer(com.twilio.video.VideoRenderer)' on a null object reference
       at com.zenmd.ui.twilio.video.VideoActivity.moveLocalVideoToThumbnailView(VideoActivity.java:292)
       at com.zenmd.ui.twilio.video.VideoActivity.addParticipantVideo(VideoActivity.java:284)
       at com.zenmd.ui.twilio.video.VideoActivity.access$800(VideoActivity.java:35)
       at com.zenmd.ui.twilio.video.VideoActivity$2.onVideoTrackAdded(VideoActivity.java:411)
       at com.twilio.video.Participant$1$3.run(Participant.java:102)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

#### Video Android SDK
1.3.0

#### Android API
any

**Comment by aaalaniz** [comment]
Hey @PingForward 

Thanks for the detailed steps to reproduce. I will submit a PR fixing this issue.

Thanks!
