### ISSUE TITLE
Getting a crash while using VideoView backed by TextureView.. 

### ISSUE THREAD

**Issue by shivthepro** [twilio/video-quickstart-android#250]
### Description

Getting a crash while using VideoView backed by TextureView. Crash Occurs when I try to change orientation of mobile continuously.

### Steps to Reproduce

1. Use a VideoView backed by textureView [https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e](click here)
2. Create a room and land into the call page which has the VideoView in it.. 
3. Try rotating the mobile and changing orientation of the mobile from portrait to landscape continuously or in a 3 second interval.

#### Logs which I got

```
 FATAL EXCEPTION: main
    Process: com.example.twiliovideo , PID: 2448
    java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14.createEglContext(EglBase14.java:260)
        at org.webrtc.EglBase14.<init>(EglBase14.java:58)
        at org.webrtc.EglBase.create(EglBase.java:86)
        at org.webrtc.EglRenderer$3.run(EglRenderer.java:194)
        at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:208)
        at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:205)
        at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:182)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:193)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:205)
        at org.webrtc.EglRenderer.init(EglRenderer.java:183)
        at com.example.twiliovideo.twilio_custom.TextureVideoView.init(TextureVideoView.java:200)
        at com.example.twiliovideo.twilio_custom.TextureVideoView.init(TextureVideoView.java:186)
        at com.example.twiliovideo.twilio_custom.TextureVideoView.onAttachedToWindow(TextureVideoView.java:98)
        at android.view.View.dispatchAttachedToWindow(View.java:16718)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4697)
        at android.view.ViewGroup.addView(ViewGroup.java:4499)
        at android.view.ViewGroup.addView(ViewGroup.java:4439)
        at android.view.ViewGroup.addView(ViewGroup.java:4412)
        at com.example.twiliovideo.ui.activities.VideoCallActivity.createSelfVideoView(VideoCallActivity.java:1189)
        at com.example.twiliovideo.ui.activities.VideoCallActivity.initializeRoom(VideoCallActivity.java:1160)
        at com.example.twiliovideo.ui.activities.VideoCallActivity.access$4600(VideoCallActivity.java:88)
        at com.example.twiliovideo.ui.activities.VideoCallActivity$RoomServiceConnection.onServiceConnected(VideoCallActivity.java:1539)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1516)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1544)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14.createEglContext(EglBase14.java:260)
        at org.webrtc.EglBase14.<init>(EglBase14.java:58)
        at org.webrtc.EglBase.create(EglBase.java:86)
        at org.webrtc.EglRenderer$3.run(EglRenderer.java:194)
        at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:208)
        at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:205)
        at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:182)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

```

#### Video Android SDK
2.0.0-preview7

#### Android API
Api 24

#### Android Device
Samsung C7 Pro ... The issue generally occurs with all devices.

**Comment by aaalaniz** [comment]
Hey @shivthepro 

Are you allowing the activity to be destroyed on orientation changes or are you using `android:configChanges="orientation|screenSize"` in your AndroidManifest.xml?

Thanks!

**Comment by shivthepro** [comment]
Tried this but the same issue occurs again..

**Comment by shivthepro** [comment]
@aaalaniz  I have tried adding the configChanges.. But it does not help in solving the issue.. having the problem.. Can you please check into it.

**Comment by aaalaniz** [comment]
Does this crash occur with our regular VideoView? This will take me some time as `VideoTextureView` is not part of our SDK.

**Comment by zackm0571** [comment]
@shivthepro we recently just released version `2.2.0` of our SDK which has `VideoTextureView`. Could you give this a shot and see if it fixes your crash?

**Comment by zackm0571** [comment]
Closing due to inactivity. Please let us know if you can reproduce this.

**Comment by dephizee** [comment]
> Does this crash occur with our regular VideoView? This will take me some time as `VideoTextureView` is not part of our SDK.

I think this is the issue I've encountering, regular videoview works, but twilio videoview crashes the app
