### ISSUE TITLE
Error while using VideoTextureView in RecyclerView

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#257]
### Description

I get a crash while scrolling videos in Recycler view of TextureViews.

### Steps to Reproduce

1. Scroll the list of videos

#### Expected Behavior

App should not crash

#### Actual Behavior

App crashes

#### Reproduces how Often

100%

#### Logs

```
Fatal Exception: java.lang.IllegalStateException: video_view: Already initialized
       at org.webrtc.EglRenderer.init(EglRenderer.java:172)
       at to.go.ui.utils.views.VideoTextureView.init(VideoTextureView.java:170)
       at to.go.ui.utils.views.VideoTextureView.init(VideoTextureView.java:156)
       at to.go.ui.utils.views.VideoTextureView.onAttachedToWindow(VideoTextureView.java:88)
       at android.view.View.dispatchAttachedToWindow(View.java:17483)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3330)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3330)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3330)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4959)
       at android.view.ViewGroup.addView(ViewGroup.java:4750)
       at android.view.ViewGroup.addView(ViewGroup.java:4690)
       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:746)
       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8003)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7961)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1572)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:759)
       at android.view.View.layout(View.java:19692)
       at android.view.ViewGroup.layout(ViewGroup.java:6057)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2515)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2224)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1410)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6834)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:778)
       at android.view.Choreographer.doFrame(Choreographer.java:713)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6809)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

#### Video Android SDK

2.0.0-preview 5

#### Android API

26

#### Android Device

OnePlus, Xiaomi

**Comment by aaalaniz** [comment]
Hey @rishabhja 

Does this same crash occur when using our normal `VideoView`? Can you reference my [RecyclerView](https://gist.github.com/aaalaniz/b779b12d2887c32576ffa4d5828b88c1) example? 

Thanks

**Comment by rishabhja** [comment]
It does not occur with VideoView

**Comment by rishabhja** [comment]
Any update on this?

**Comment by aaalaniz** [comment]
Apologies, but no update on this effort. Based on the log, have you tried using a flag to prevent init from being called more than once?

**Comment by rishabhja** [comment]
I will try that and update you

**Comment by mayurvpatel** [comment]
@aaalaniz Yes I got this same error in group call. While one user join and exit in one group more than 2 to 3 time that time  i am getting this error. Pls can you give me some solution for this. And this is my SID "RM2277db4f451bee6634a5132be679a8d9"

I am using this  VideoTextureView for rendering video of number of connected users in room.
https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e
