### ISSUE TITLE
Crash on camera flip in emulator

### ISSUE THREAD

**Issue by mwajeeh** [twilio/video-quickstart-android#278]
### Description
App crashes when trying to flip camera on emulator

### Steps to Reproduce

1. Try to flip camera on Emulator

#### Code

```
// Code that help reproduce the issue
ParticipantRenderer.flipCamera()
```
#### Expected Behavior

Camera should switch or app shouldn't crash

#### Actual Behavior
App crashes

#### Reproduces how Often

100%

#### Logs

``` 
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.twilio.video.VideoCapturerListenerAdapter.onFrameCaptured(VideoCapturerListenerAdapter.java:47)
        at com.twilio.video.CameraCapturer$1.onByteBufferFrameCaptured(CameraCapturer.java:182)
        at org.webrtc.CameraCapturer$2.onByteBufferFrameCaptured(CameraCapturer.java:159)
        at org.webrtc.Camera1Session$3.onPreviewFrame(Camera1Session.java:301)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1124)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
``` 

#### Video Android SDK
com.twilio:video-android:1.3.13

#### Android API
API level 26

#### Android Device
Emulator Android 8.0 x86

**Comment by aaalaniz** [comment]
Hey @mwajeeh 

Can you be more specific with the code that reproduces the issue by providing the source for `ParticipantRenderer.flipCamera()` ?

Thanks!

**Comment by aaalaniz** [comment]
Closing due to inactivity. Please reopen if you have any more questions @mwajeeh. Thanks!
