### ISSUE TITLE
Camera Freezing issue during video call | Android

### ISSUE THREAD

**Issue by rakeshkatta1311** [twilio/video-quickstart-android#318]
I am facing an issue in Android Video Calling functionality. In RealWear android device, camera is being stopped  during the video call. This is working fine in all other devices. 

Issue is: Tried to call from Realwear device to any other device. Call connected between two user. Now sometimes the camera is being stopped in RealWear device and at opponent side screen is being black.  
This issue is random, I don't have any special case to reproduce it but this is frequent issue.

Please let us know Does Twilio sdk is using Camera 1 API with HAL3?

Below are the some logs while getting this issue.

05-04 15:07:54.856 20462-22187/blitzz.co.blitzztest E/org.webrtc.Logging: MediaCodecVideoEncoder: java.lang.IllegalStateException at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method) at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379) at org.webrtc.MediaCodecVideoEncoder.dequeueOutputBuffer(MediaCodecVideoEncoder.java:668)

I have checked that whenever this issue is occurred, getting the value of camera Stat is 1 (STAT==STOPPING). To get it out I have tried to release the camera, un-publishing the video track and than recreating the video track and publishing it again. But unfortunately it won't work. So is there any way to reassign the camera during a call?

Device Details:
Realwear HMT-1 Smart glass [(See details)](https://www.realwear.com/products/hmt-1)  

Android Os:  6.0.1 API 23

Twilo SDK Version: com.twilio:video-android:2.0.2

Please let me know if any thing else is required from my side to solve this issue.

Thanks,
Rakesh

**Comment by idelgado** [comment]
Hey here are a few things to try:

1. Explicitly use `CameraCapturer2`. If your code is using [CameraCapturerCompat](https://github.com/twilio/video-quickstart-android/blob/cb9630779bfba9ce9180bac5057efaf648aa8858/quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java#L16) from the quickstart example then I would expect a device with Android OS API 23 to use Camera2 APIs. However if you are instantiating the `LocalVideoTrack` with a `CameraCapturer` instance instead then it will use Camera1 APIs.

   To force the usage of Camera2 APIs you can do the following:
   ```
   Camera2Capturer camera2Capturer = new Camera2Capturer(context,
                    CameraCapturer.CameraSource.FRONT_CAMERA,
                    camera2Listener);
   LocalVideoTrack localVideoTrack = LocalVideoTrack.create(this, true, camera2Capturer);
   ```

2. Try `com.twilio:video-android:3.0.0-preview1`. This uses WebRTC 67 which is a newer capturer pipeline for the camera. Make sure you also use `Camera2Capturer` here as well.

3. The error log implies that there is some issue with the decoder, are you using the default codec of VP8? If you can provide a full log from the very beginning of using the Video Android SDK we can see what settings are being used. Please provide a log by first calling this:

   ```
   Video.setLogLevel(LogLevel.ALL);
   ```

**Comment by rakeshkatta1311** [comment]
Hi,

Thanks for your response.

I have changed first 2 points and testing it. 

Yes, I'm using VP8 codec.  Here is the log file of start call to end call process. [Log file](https://drive.google.com/open?id=1408XXehTbpL9etUTyqMqluJSVbV6aSmz)

Thanks,
Rakesh

**Comment by rakeshkatta1311** [comment]
Hi,

Still I'm facing this issue. 

Please check attached log file when camera is stopped during video call.

[Stucked camera log.txt](https://github.com/twilio/video-quickstart-android/files/2286607/Stucked.camera.log.txt)

Thanks,
Rakesh

**Comment by rakeshkatta1311** [comment]
Hi,

Below is the code of CameraCapturerCompat.

```
package TwilioCallClasses;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.hardware.Camera;
import android.support.annotation.NonNull;
import android.util.Log;
import android.util.Pair;

import com.quickblox.chat.model.QBChatMessage;
import com.twilio.video.Camera2Capturer;
import com.twilio.video.CameraCapturer;
import com.twilio.video.CameraParameterUpdater;
import com.twilio.video.VideoCapturer;
import com.twilio.video.VideoFormat;

import org.json.JSONObject;
import org.webrtc.Camera2Enumerator;

import java.util.List;

/*
 * Simple wrapper class that uses Camera2Capturer with supported devices.
 */
public class CameraCapturerCompat {
    private static final String TAG = "CameraCapturerCompat";

    private CameraCapturer camera1Capturer;
    private Camera2Capturer camera2Capturer;
    private SwitchcameraListner switchcameraListner;
    private boolean flashOn = false;
    private Pair<CameraCapturer.CameraSource, String> frontCameraPair;
    private Pair<CameraCapturer.CameraSource, String> backCameraPair;
//    private setBitmap imageListener;

    public CameraCapturerCompat(Context context,
                                CameraCapturer.CameraSource cameraSource, final SwitchcameraListner switchcameraListner) {
        this.switchcameraListner = switchcameraListner;
        camera2Capturer = new Camera2Capturer(context, getCameraId(cameraSource), new Camera2Capturer.Listener() {
            @Override
            public void onFirstFrameAvailable() {
                Log.i(TAG, "onFirstFrameAvailable");
            }

            @Override
            public void onCameraSwitched(@NonNull String newCameraId) {
                if (switchcameraListner != null) {
                    switchcameraListner.onCameraSwitched("");
                }
                Log.i(TAG, "onCameraSwitched: newCameraId = " + "");
            }

            @Override
            public void onError(@NonNull Camera2Capturer.Exception camera2CapturerException) {
            }

        });
    }

    private String getCameraId(CameraCapturer.CameraSource cameraSource) {
        if (frontCameraPair.first == cameraSource) {
            return frontCameraPair.second;
        } else {
            return backCameraPair.second;
        }
    }

    // Schedule camera parameter update

//    public void updateCamera() {
//
//        camera1Capturer.updateCameraParameters(new CameraParameterUpdater() {
//            @Override
//            public void apply(Camera.Parameters cameraParameters) {
//                // Ensure camera supports flash and turn on
//                if (cameraParameters.getFlashMode() != null) {
//                    cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
//                }
//            }
//        });
//    }

    /**
     * An example of a {@link CameraParameterUpdater} that shows how to toggle the flash of a
     * camera if supported by the device.
     */
    private CameraParameterUpdater getFlashToggler(final boolean isFlashon) {
        CameraParameterUpdater flashToggler = new CameraParameterUpdater() {
            @Override
            public void apply(Camera.Parameters parameters) {
                if (parameters.getFlashMode() != null) {
                    String flashMode = isFlashon ?
                            Camera.Parameters.FLASH_MODE_TORCH :
                            Camera.Parameters.FLASH_MODE_OFF;
                    parameters.setFlashMode(flashMode);
                } else {
                    Log.e(TAG, "Flash is not Supported");
                }
            }
        };
        return flashToggler;
    }

    public void toggleFlash(boolean isFlashon) {
        try {
            // Request an update to camera parameters with flash toggler
            CameraParameterUpdater flashToggler = getFlashToggler(isFlashon);
//            camera1Capturer.updateCameraParameters(flashToggler);
        } catch (Exception e) {
            Log.e(TAG, e.toString());
        }
    }

//    public void getIsFlahon(){
//        camera1Capturer.getCameraSource();
//    }
//
//    public void switchCamera() {
//        if (usingCamera1()) {
//            camera1Capturer.switchCamera();
//        } else {
//            CameraCapturer.CameraSource cameraSource = getCameraSource(camera2Capturer
//                    .getCameraId());
//
//            if (cameraSource == CameraCapturer.CameraSource.FRONT_CAMERA) {
//                camera2Capturer.switchCamera(backCameraPair.second);
//            } else {
//                camera2Capturer.switchCamera(frontCameraPair.second);
//            }
//        }
//    }

    public void getBitmap(final OnScreenshotOfLocalstream onScreenshotOfLocalstream, final JSONObject jsonObject) {

        final Bitmap[] bitmap = {null};
//        camera1Capturer.takePicture(new CameraCapturer.PictureListener() {
//            @Override
//            public void onShutter() {
//                // Show some UI or play a sound
//            }
//
//            @Override
//            public void onPictureTaken(byte[] pictureData) {
//                bitmap[0] = BitmapFactory.decodeByteArray(pictureData, 0,
//                        pictureData.length);
//                onScreenshotOfLocalstream.bitmapTaken(bitmap[0],jsonObject);
//            }
//        });
    }

    public List<VideoFormat> getSupportedFormats() {
        if (camera2Capturer != null)
            return camera2Capturer.getSupportedFormats();
        return null;
    }


    //    private Bitmap bitmap = null;
//    private final CameraCapturer.PictureListener photographer =
//            new CameraCapturer.PictureListener() {
//                @Override
//                public void onShutter() {
//
//                }
//
//                @Override
//                public void onPictureTaken(byte[] bytes) {
//                    imageListener.getBitmap(bytes);
//                }
//            };

    public CameraCapturer.CameraSource getCameraSource() {
        if (usingCamera1()) {
            return camera1Capturer.getCameraSource();
        } else {
            return getCameraSource(camera2Capturer.getCameraId());
        }
    }

    public VideoCapturer getVideoCapturer() {
        if (usingCamera1()) {
            return camera1Capturer;
        } else {
            return camera2Capturer;
        }
    }

    private boolean usingCamera1() {
        return camera1Capturer != null;
    }

//    private void setCameraPairs(Context context) {
//        Camera2Enumerator camera2Enumerator = new Camera2Enumerator(context);
//        for (String cameraId : camera2Enumerator.getDeviceNames()) {
//            if (camera2Enumerator.isFrontFacing(cameraId)) {
//                frontCameraPair = new Pair<>(CameraCapturer.CameraSource.FRONT_CAMERA, cameraId);
//            }
//            if (camera2Enumerator.isBackFacing(cameraId)) {
//                backCameraPair = new Pair<>(CameraCapturer.CameraSource.BACK_CAMERA, cameraId);
//            }
//        }
//    }

//    private String getCameraId(CameraCapturer.CameraSource cameraSource) {
////        if (frontCameraPair.first == cameraSource) {
////            return frontCameraPair.second;
////        } else {
//        return "0";
////        }
//    }

    public CameraCapturer.CameraSource getCameraSource(String cameraId) {
        if (frontCameraPair.second.equals(cameraId)) {
            return frontCameraPair.first;
        } else {
            return backCameraPair.first;
        }
    }

//    public void takePic(setBitmap imageListener) {
//        this.imageListener = imageListener;
//        camera1Capturer.takePicture(photographer);
//    }

//    interface setBitmap {
//        void getBitmap(byte[] bytes);
//    }

    public interface SwitchcameraListner {
        void onCameraSwitched(String newCameraId);
    }
}
```

To create LocalVideoTrack I have used below code.

  ```
public LocalVideoTrack createVideoTracks(Activity activity) {
        try {
            cameraCapturerCompat = new CameraCapturerCompat(activity, getAvailableCameraSource(), switchcameraListner);
//            List<VideoFormat> supportedFormats = cameraCapturerCompat.getSupportedFormats();
            Video.setLogLevel(LogLevel.ALL);
            VideoConstraints videoConstraints = getConstraint();
            if (videoConstraints != null) {
                  localVideoTrack = LocalVideoTrack.create(activity, true, cameraCapturerCompat.getVideoCapturer(), videoConstraints);
                return localVideoTrack;
            } else {
                return null;
            }
        } catch (Exception e) {
            Log.e(TAG, e.toString());
            return null;
        }
    }
```

Thanks,
Rakesh

**Comment by idelgado** [comment]
Do you have a log for this code? Is `CameraCapturerCompat` resulting in using `Camera1`? If so using the snippet highlighted in bullet 1 above can force the usage of Camera2. It is possible that the underlying camera does not support Camera2. Another way to check this is to use Camera2 on it's own and see if it is supported.

**Comment by rakeshkatta1311** [comment]
Hi,

Provided log file is of the above code. 

We have made changes suggested by you and using `com.twilio:video-android:3.0.0-preview1`  dependency. I'm getting a black screen during video call all the time. Is there any change in this dependency? 

Thanks,
Rakesh

**Comment by idelgado** [comment]
Is this for both the LocalVideoTrack and RemoteVideoTrack(s) from Participants? Please provide logs and a code snippet with this setting `Video.setLogLevel(LogLevel.ALL);`

**Comment by rakeshkatta1311** [comment]
Hi,

Any workaround to solve this?

Thanks,
Rakesh

**Comment by idelgado** [comment]
Hey, unfortunately the log you provided doesn't have any logs from the Video SDK. I see logs from your app but no longs from the Video SDK.

With the snippet set below there should be logs from the Camera2Capturer when it is initialized.

```Java
Video.setLogLevel(LogLevel.ALL);
Video.setModuleLogLevel(LogModule.WEBRTC, LogLevel.ALL);
```

**Comment by zackm0571** [comment]
Closing. Please reopen if you're still having issues. :)
