### ISSUE TITLE
CameraCapturer: onCameraError from another session: startPreview failed

### ISSUE THREAD

**Issue by jishindev** [twilio/video-quickstart-android#376]
I might be missing something. Would really appreciate if you guys could guide me here. 

library version: 3.2.1
studio: AS 3.4 beta1
device: Lenovo TB3-X70L

```
01-29 19:23:36.458 I/VideoCallActivity: connectToRoom() called with: roomName = [test]
01-29 19:23:36.459 W/VideoTextureView: Scale type may not be applied as expected because video view uses MATCH_PARENT. Scaling will be applied as follows: width=ASPECT_FILL, height=ASPECT_FILL
01-29 19:23:36.575 I/VideoCallActivity$conne: connectToRoom: permissions granted
01-29 19:23:36.575 I/org.webrtc.Logging: EglRenderer: vtvLocal: setMirror: true
01-29 19:23:36.591 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:36.592 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:36.593 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:36.594 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:36.596 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:36.604 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:36.605 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:36.605 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:36.607 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:36.608 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:36.642 I/CameraFramework: Camera framework getParameters =3dnr-mode=on;3dnr-mode-values=on,off;afeng-max-focus-step=1023;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,asd,motiontrack;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;dynamic-frame-rate=true;dynamic-frame-rate-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard,posterize,nashville,hefe,valencia,xproll,lofi,sierra,walden;eng-mfll-e=false;eng-mfll-s=true;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;face-beauty=false;face-beauty-supported=true;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-extreme-beauty-supported=false;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-default=-3;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-default=3;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;feature-max-fps=24@VFB+EIS;first-preview-frame-black=0;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-mode=off;flash-mode-values=off;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=auto;focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;gesture-shot=false;gesture-shot-supported=false;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=0;max-zoom=10;mfb=off;mfb-values=off,ais;min-exposure-compensation=-3;mnr-e=0;mnr-s=true;mtk-123-shad-s=true;mtk-awb-s=true;mtk-cam-mode=0;mtk-shad-s=true;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=1600x1200;picture-size-values=176x144,320x240,640x480,1024x768,1280x720,1280x768,1600x960,1280x960,1600x1200,1920x1088,2048x1536,2560x1440,2560x1920,2880x1728;pip-fps-zsd-off=30;pip-fps-zsd-on=15;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(5000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,20,30,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,1280x720,1280x960,1440x1080,1920x1080,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=252;smooth-zoom-supported=true;sr-awb-s=true;sr-shad-s=true;stereo-capture-frame-rate=15;stereo-preview-frame-rate=15;sv1-s=3;sv2-s=3;vdr-cc2m-s=true;vdr-r=0;vdr-r2m-s=true;vdr-r4k2k-s=true;vertical-view-angle=40;vfb-supported=true;vfb-supported-values=true;video-frame-format=yuv420p;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,640x480,720x480,1280x72
01-29 19:23:36.920 I/org.webrtc.Logging: EglRenderer: vtvRemote: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA.
01-29 19:23:36.920 I/org.webrtc.Logging: EglRenderer: vtvLocal: Duration: 4002 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA.
01-29 19:23:37.362 W/AudioCapabilities: Unsupported mime audio/mpeg-L2
01-29 19:23:37.363 W/AudioCapabilities: Unsupported mime audio/x-adpcm-ms
01-29 19:23:37.364 W/AudioCapabilities: Unsupported mime audio/x-adpcm-dvi-ima
01-29 19:23:37.368 W/AudioCapabilities: Unsupported mime audio/ape
01-29 19:23:37.368 W/AudioCapabilities: Unsupported mime audio/alac
01-29 19:23:37.369 W/AudioCapabilities: Unsupported mime audio/ac3
01-29 19:23:37.370 W/AudioCapabilities: Unsupported mime audio/eac3
01-29 19:23:37.371 W/AudioCapabilities: Unsupported mime audio/eac3-joc
01-29 19:23:37.373 W/AudioCapabilities: Unsupported mime audio/x-adpcm-ms
01-29 19:23:37.374 W/AudioCapabilities: Unsupported mime audio/x-adpcm-dvi-ima
01-29 19:23:37.379 W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
01-29 19:23:37.387 W/VideoCapabilities: Unsupported mime video/x-ms-wmv
01-29 19:23:37.389 W/VideoCapabilities: Unsupported mime video/divx
01-29 19:23:37.391 W/VideoCapabilities: Unsupported mime video/divx3
01-29 19:23:37.393 W/VideoCapabilities: Unsupported mime video/xvid
01-29 19:23:37.394 W/VideoCapabilities: Unsupported mime video/flv1
01-29 19:23:37.421 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
01-29 19:23:37.429 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/avc
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.MTK.VIDEO.DECODER.AVC
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.h264.decoder
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/avc
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/avc
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.MTK.VIDEO.DECODER.AVC
01-29 19:23:37.430 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.h264.decoder
01-29 19:23:37.431 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/avc
01-29 19:23:37.431 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/x-vnd.on2.vp8
01-29 19:23:37.431 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.MTK.VIDEO.DECODER.VPX
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.vp8.decoder
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/x-vnd.on2.vp8
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/x-vnd.on2.vp9
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.MTK.VIDEO.DECODER.VP9
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.vp9.decoder
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/x-vnd.on2.vp9
01-29 19:23:37.432 I/org.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/avc
01-29 19:23:37.433 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.MTK.VIDEO.DECODER.AVC
01-29 19:23:37.433 I/org.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.google.h264.decoder
01-29 19:23:37.433 I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW decoder found for mime video/avc
01-29 19:23:37.440 I/org.webrtc.Logging: WebRtcAudioManager: ctor@[name=Thread-5374, id=5374]
01-29 19:23:37.443 I/org.webrtc.Logging: WebRtcAudioManager: Sample rate is set to 44100 Hz
01-29 19:23:37.450 I/org.webrtc.Logging: WebRtcAudioEffects: canUseAcousticEchoCanceler: false
01-29 19:23:37.450 I/org.webrtc.Logging: WebRtcAudioEffects: canUseNoiseSuppressor: false
01-29 19:23:37.451 W/org.webrtc.Logging: WebRtcAudioManager: AAudio support is currently disabled on all devices!
01-29 19:23:37.452 D/AudioRecord: getMinFrameCount 1024
01-29 19:23:37.452 I/org.webrtc.Logging: WebRtcAudioManager: Android SDK: 23, Release: 6.0, Brand: Lenovo, Device: TB3-X70L, Id: MRA58K, Hardware: mt6735, Manufacturer: LENOVO, Model: Lenovo TB3-X70L, Product: LenovoTB3-X70L
01-29 19:23:37.454 I/org.webrtc.Logging: WebRtcAudioManager: Audio State: audio mode: MODE_NORMAL, has mic: true, mic muted: false, music active: false, speakerphone: false, BT SCO: false
01-29 19:23:37.454 I/org.webrtc.Logging: WebRtcAudioManager: Audio State: 
01-29 19:23:37.454 I/org.webrtc.Logging: WebRtcAudioManager:   fixed volume=false
01-29 19:23:37.455 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_VOICE_CALL: volume=4, max=7, muted=false
01-29 19:23:37.455 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_MUSIC: volume=8, max=15, muted=false
01-29 19:23:37.456 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_RING: volume=4, max=7, muted=false
01-29 19:23:37.457 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_ALARM: volume=8, max=15, muted=false
01-29 19:23:37.457 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_NOTIFICATION: volume=9, max=15, muted=false
01-29 19:23:37.458 I/org.webrtc.Logging: WebRtcAudioManager:   STREAM_SYSTEM: volume=4, max=7, muted=false
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager: Audio Devices: 
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager:   TYPE_BUILTIN_SPEAKER(out): id=2
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager:   TYPE_BUILTIN_EARPIECE(out): id=1
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager:   TYPE_BUILTIN_MIC(in): channels=[1, 2], encodings=[2], sample rates=[8000, 16000, 32000, 44100, 48000], id=5
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager:   TYPE_FM_TUNER(in): channels=[1, 2], encodings=[2], sample rates=[8000, 16000, 32000, 44100, 48000], id=7
01-29 19:23:37.460 I/org.webrtc.Logging: WebRtcAudioManager:   TYPE_TELEPHONY(in): channels=[1, 2], encodings=[2], sample rates=[8000, 16000, 32000, 44100, 48000], id=6
01-29 19:23:37.464 I/org.webrtc.Logging: WebRtcAudioTrack: ctor@[name=Thread-5374, id=5374]
01-29 19:23:37.467 I/org.webrtc.Logging: WebRtcAudioRecord: ctor@[name=Thread-5374, id=5374]
01-29 19:23:37.467 I/org.webrtc.Logging: WebRtcAudioEffects: ctor@[name=Thread-5374, id=5374]
01-29 19:23:37.467 I/org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-5374, id=5374]
01-29 19:23:37.467 I/org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_NORMAL
01-29 19:23:37.470 E/LocalVideoTrack: Applying VideoConstraints closest to 640x480@30 FPS.
01-29 19:23:37.476 I/org.webrtc.Logging: EglBase14: SDK version: 23. isEGL14Supported: true
01-29 19:23:37.483 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:37.488 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:37.489 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.490 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.492 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:37.495 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:37.495 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:37.503 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:37.504 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:37.504 I/org.webrtc.Logging: CameraCapturer: startCapture: 640x480@30
01-29 19:23:37.505 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:37.511 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:37.511 I/org.webrtc.Logging: Camera1Session: Open camera 1
01-29 19:23:37.513 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:37.513 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.539 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.540 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:37.545 I/CameraFramework: Camera framework getParameters =3dnr-mode=on;3dnr-mode-values=on,off;afeng-max-focus-step=1023;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,asd,motiontrack;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;dynamic-frame-rate=true;dynamic-frame-rate-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard,posterize,nashville,hefe,valencia,xproll,lofi,sierra,walden;eng-mfll-e=false;eng-mfll-s=true;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;face-beauty=false;face-beauty-supported=true;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-extreme-beauty-supported=false;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-default=-3;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-default=3;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;feature-max-fps=24@VFB+EIS;first-preview-frame-black=0;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-mode=off;flash-mode-values=off;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=auto;focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;gesture-shot=false;gesture-shot-supported=false;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=0;max-zoom=10;mfb=off;mfb-values=off,ais;min-exposure-compensation=-3;mnr-e=0;mnr-s=true;mtk-123-shad-s=true;mtk-awb-s=true;mtk-cam-mode=0;mtk-shad-s=true;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=1600x1200;picture-size-values=176x144,320x240,640x480,1024x768,1280x720,1280x768,1600x960,1280x960,1600x1200,1920x1088,2048x1536,2560x1440,2560x1920,2880x1728;pip-fps-zsd-off=30;pip-fps-zsd-on=15;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(5000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,20,30,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,1280x720,1280x960,1440x1080,1920x1080,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=252;smooth-zoom-supported=true;sr-awb-s=true;sr-shad-s=true;stereo-capture-frame-rate=15;stereo-preview-frame-rate=15;sv1-s=3;sv2-s=3;vdr-cc2m-s=true;vdr-r=0;vdr-r2m-s=true;vdr-r4k2k-s=true;vertical-view-angle=40;vfb-supported=true;vfb-supported-values=true;video-frame-format=yuv420p;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,640x480,720x480,1280x72
01-29 19:23:37.547 I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
01-29 19:23:37.548 I/org.webrtc.Logging: Camera1Session: Available fps ranges: [[15.0:15.0], [20.0:20.0], [5.0:30.0], [30.0:30.0]]
01-29 19:23:37.548 I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 180
01-29 19:23:37.549 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.550 V/CameraFramework: set Key = preview-fps-range, value = 5000,30000
01-29 19:23:37.550 V/CameraFramework: set Key = preview-size, value = 640x480
01-29 19:23:37.550 V/CameraFramework: set Key = picture-size, value = 640x480
01-29 19:23:37.551 V/CameraFramework: set Key = preview-format, value = yuv420sp
01-29 19:23:37.551 V/CameraFramework: set Key = video-stabilization, value = true
01-29 19:23:37.551 V/CameraFramework: set Key = focus-mode, value = continuous-video
01-29 19:23:37.556 I/org.webrtc.Logging: Camera1Session: Create new camera1 session on camera 1
01-29 19:23:37.556 I/org.webrtc.Logging: Camera1Session: Start capturing
01-29 19:23:37.557 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
01-29 19:23:37.560 I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-29 19:23:38.564 I/org.webrtc.Logging: CameraCapturer: Create session done. Switch state: IDLE. MediaRecorder state: IDLE
01-29 19:23:38.565 I/CameraFramework: handleMessage: 1
01-29 19:23:38.565 E/CameraFramework: Error 2
01-29 19:23:38.565 E/org.webrtc.Logging: Camera1Session: Camera error: 2
01-29 19:23:38.565 I/org.webrtc.Logging: Camera1Session: Stop internal
01-29 19:23:38.566 I/org.webrtc.Logging: SurfaceTextureHelper: stopListening()
01-29 19:23:38.796 I/org.webrtc.Logging: Camera1Session: Stop done
01-29 19:23:38.796 I/org.webrtc.Logging: CameraCapturer: Stop capture
01-29 19:23:38.796 I/org.webrtc.Logging: CameraCapturer: Stop capture: Nulling session
01-29 19:23:38.797 I/org.webrtc.Logging: CameraCapturer: Stop capture done
01-29 19:23:38.798 I/org.webrtc.Logging: Camera1Session: Stop camera1 session on camera 1
01-29 19:23:38.848 I/CameraFramework: Camera framework getParameters =3dnr-mode=on;3dnr-mode-values=on,off;afeng-max-focus-step=1023;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,asd,motiontrack;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;dynamic-frame-rate=true;dynamic-frame-rate-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard,posterize,nashville,hefe,valencia,xproll,lofi,sierra,walden;eng-mfll-e=false;eng-mfll-s=true;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;face-beauty=false;face-beauty-supported=true;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-extreme-beauty-supported=false;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-default=-3;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-default=3;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;feature-max-fps=24@VFB+EIS;first-preview-frame-black=0;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-mode=off;flash-mode-values=off;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=auto;focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;gesture-shot=false;gesture-shot-supported=false;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=0;max-zoom=10;mfb=off;mfb-values=off,ais;min-exposure-compensation=-3;mnr-e=0;mnr-s=true;mtk-123-shad-s=true;mtk-awb-s=true;mtk-cam-mode=0;mtk-shad-s=true;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=1600x1200;picture-size-values=176x144,320x240,640x480,1024x768,1280x720,1280x768,1600x960,1280x960,1600x1200,1920x1088,2048x1536,2560x1440,2560x1920,2880x1728;pip-fps-zsd-off=30;pip-fps-zsd-on=15;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(5000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,20,30,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,1280x720,1280x960,1440x1080,1920x1080,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=252;smooth-zoom-supported=true;sr-awb-s=true;sr-shad-s=true;stereo-capture-frame-rate=15;stereo-preview-frame-rate=15;sv1-s=3;sv2-s=3;vdr-cc2m-s=true;vdr-r=0;vdr-r2m-s=true;vdr-r4k2k-s=true;vertical-view-angle=40;vfb-supported=true;vfb-supported-values=true;video-frame-format=yuv420p;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,640x480,720x480,1280x72
01-29 19:23:39.519 E/LocalVideoTrack: Applying VideoConstraints closest to 640x480@30 FPS.
```

**Comment by jishindev** [comment]
Also this one seems to be popping up now - 
```
org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 180
01-30 19:10:07.361 E/AndroidRuntime: FATAL EXCEPTION: Camera SurfaceTextureHelper
    Process: com.creoit.android.slate.slatestaff, PID: 7976
    java.lang.RuntimeException: set display orientation failed
        at android.hardware.Camera.setDisplayOrientation(Native Method)
        at org.webrtc.Camera1Session.create(Camera1Session.java:104)
        at org.webrtc.Camera1Capturer.createCameraSession(Camera1Capturer.java:32)
        at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:306)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jishindev** [comment]
Apologies. I had my localvideotrack initialization code in a lazy delegate which was giving me a lot of errors. It's been resolved now. 

Thank you.

**Comment by mark922** [comment]
@jishindev I am facing a similar issue. Can you elaborate on how did you solve this?
