### ISSUE TITLE
Failed to create window surface

### ISSUE THREAD

**Issue by palimad** [twilio/video-quickstart-android#387]
Fatal Exception: java.lang.RuntimeException
Failed to create window surface: 0x300b
org.webrtc.EglBase14.createSurfaceInternal (EglBase14.java:104)
org.webrtc.EglBase14.createSurface (EglBase14.java:82)
org.webrtc.EglRenderer$EglSurfaceCreation.run (EglRenderer.java:70)
android.os.Handler.handleCallback (Handler.java:789)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:164)
android.os.HandlerThread.run (HandlerThread.java:65)

I get this error on Crashlytics, not sure where it could came up from. Perhaps some track is trying to paint on view that was destroyed?

**Comment by zackm0571** [comment]
Hey @palimad,

Couple questions for you to help me understand:
- Are you able to reproduce this crash locally? 
- Could you provide the code where this is happening?
- What version of the SDK are you running?
- Are you using `VideoView` or `VideoTextureView`?

Hope we can get this resolved for you :)

**Comment by palimad** [comment]
Hello unfortunately I am not. I use SDK version 4.0.0 and VideoView. Do you observe less issues with VideoTextureView?

**Comment by palimad** [comment]
I got some surrounding logs, perhaps they could be useful:
2019-03-14 12:20:03.853 15824-16333/com.xxx E/org.webrtc.Logging: MediaCodecVideoDecoder: Very high decode time: 819ms. Q size: 4. Might be caused by resuming H264 decoding after a pause.
2019-03-14 12:20:03.986 1143-1215/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2019-03-14 12:20:03.992 1810-1810/? E/PhoneInterfaceManager: [PhoneIntfMgr] queryModemActivityInfo: Empty response
2019-03-14 12:20:04.007 1143-1215/? E/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
2019-03-14 12:20:04.495 1143-1143/? E/DrmMediaResourceHelper: onRemove making Dpdrm to 0 second point 
2019-03-14 12:20:04.495 1143-1143/? E/DrmManagerClient: DRM_DISPLAYPORT_DISABLE failed
2019-03-14 12:20:04.990 575-1395/? E/BufferQueueProducer: [SurfaceView - com.xxx/com.xxx.ui.activity.main.MainActivity@3a290e@2[15824]#0] connect: BufferQueue has been abandoned
2019-03-14 12:20:04.990 15824-16410/com.xxx E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xc3dd1808) failed (0xffffffed) (already connected to another API?)
2019-03-14 12:20:04.990 15824-16410/com.xxx E/libEGL: eglCreateWindowSurface:703 error 3003 (EGL_BAD_ALLOC)
2019-03-14 12:20:04.995 15824-16410/com.xxx E/AndroidRuntime: FATAL EXCEPTION: videoViewEglRenderer
    Process: com.xxx, PID: 15824
    java.lang.RuntimeException: Failed to create window surface: 0x3003
        at org.webrtc.EglBase14.createSurfaceInternal(EglBase14.java:104)
        at org.webrtc.EglBase14.createSurface(EglBase14.java:82)
        at org.webrtc.EglRenderer$EglSurfaceCreation.run(EglRenderer.java:70)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-03-14 12:20:05.000 575-1395/? E/BufferQueueProducer: [SurfaceView - com.xxx/com.xxx.ui.activity.main.MainActivity@2e350ac@1[15824]#0] connect: BufferQueue has been abandoned
2019-03-14 12:20:05.000 15824-16411/com.xxx E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xc3c4b808) failed (0xffffffed) (already connected to another API?)
2019-03-14 12:20:05.000 15824-16411/com.xxx E/libEGL: eglCreateWindowSurface:703 error 3003 (EGL_BAD_ALLOC)
2019-03-14 12:20:05.023 572-572/? E/lowmemorykiller: Error writing /proc/15824/oom_score_adj; errno=22
2019-03-14 12:20:05.061 775-1252/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -32

**Comment by palimad** [comment]
Hello any news? It is not happening with VideoTextureView. Unfortunately on VideoTextureView there is no reusable framelistener only VideoRenderer.Listener with onFirstFrame() callback which is not good enough for me since I reuse views in my code and show overlay if they are not loaded yet. I would either need FrameListener alternative for VideoTextureView or fix of this issues ASAP as it affects real work users. Thank you

**Comment by aaalaniz** [comment]
Hey @palimad 

I think we can help provide a Listener that enables you to use `VideoTextureView` to work around this issue. Try using this gist to get frame notifications after invoking the provided `reset` method.

https://gist.github.com/aaalaniz/b0bc08765dc31265d399bdea5d30a0d6

Thanks!

**Comment by palimad** [comment]
Thanks, this has helped
