### ISSUE TITLE
Problem during simultaneous call with WhatsApp and  Twilio Video call

### ISSUE THREAD

**Issue by MukFlex** [twilio/video-quickstart-android#416]
I had implemented a Twilio video call in my application. I had tested Twilio and WhatsApp video call on  Poco F1 and Samsung J2 in two scenarios.

**1. WhatsApp Video call   established**
First I  had placed a WhatsApp call, then I placed a video call using my application from Poco and accept it on Samsung J2. My app is crash after the call connected. Sometimes it also crashes on call receive

**Exception -**

FATAL EXCEPTION: main
    Process: com.thevipgroup, PID: 18875
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thevipgroup/com.thevipgroup.call.TwilioVideoCallActivity}: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3190)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
        at android.app.ActivityThread.access$1000(ActivityThread.java:211)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6946)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service
        at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
        at com.twilio.video.CameraCapturer.getSupportedFormats(CameraCapturer.java:332)
        at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:165)
        at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:121)
        at com.thevipgroup.call.TwilioVideoCallActivity.createAudioAndVideoTracks(TwilioVideoCallActivity.java:1004)
        at com.thevipgroup.call.TwilioVideoCallActivity.joinRoom(TwilioVideoCallActivity.java:411)
        at com.thevipgroup.call.TwilioVideoCallActivity.getValuesFromIntent(TwilioVideoCallActivity.java:1130)
        at com.thevipgroup.call.TwilioVideoCallActivity.onCreate(TwilioVideoCallActivity.java:250)
        at android.app.Activity.performCreate(Activity.java:6575)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)

**2. Twilio call established**
Now I first connected the Twilo video call then WhatsApp call. WhatsApp shows an error message then terminate the call.

**WhatsApp Error Message**

![device-2019-06-06-120823](https://user-images.githubusercontent.com/26892155/59017586-84a32380-8861-11e9-9d14-9cf995c4801c.png)

**Code**

     private void createAudioAndVideoTracks() {
     
            if (localAudioTrack != null)
                return;
            // Share your microphone
            localAudioTrack = LocalAudioTrack.create(this, true, LOCAL_AUDIO_TRACK_NAME);

            // Share your camera
            cameraCapturerCompat = new CameraCapturerCompat(this, 
            getAvailableCameraSource());
            localVideoTrack = LocalVideoTrack.create(this,
                    true,
                    cameraCapturerCompat.getVideoCapturer(),
                    LOCAL_VIDEO_TRACK_NAME);
            primaryVideoView.setMirror(true);
            localVideoTrack.addRenderer(primaryVideoView);
            localVideoView = primaryVideoView;
     
       }

**Note -** I think the crash is not related to camera usages policy of Android (At a time one application can use the camera), because WhatsApp has stop video preview when put it in background.

Please state the reason and explain how to resolve this

**Comment by zackm0571** [comment]
Hey @MukFlex, 

Thanks for reaching out and putting this on our radar. We'll be investigating this afternoon. I'll let you know when we have a fix going through our pipeline. :)

Best, 

Zack

**Comment by zackm0571** [comment]
@MukFlex are you releasing the camera in `onPause`? You can do this with the following code snippet

```
   @Override
    protected void onPause() {
        /*
         * Release the local video track before going in the background. This ensures that the
         * camera can be used by other applications while this app is in the background.
         */
        if (localVideoTrack != null) {
            /*
             * If this local video track is being shared in a Room, unpublish from room before
             * releasing the video track. Participants will be notified that the track has been
             * unpublished.
             */
            if (localParticipant != null) {
                localParticipant.unpublishTrack(localVideoTrack);
            }

            localVideoTrack.release();
            localVideoTrack = null;
        }
        super.onPause();
    }
```

**Comment by MukFlex** [comment]
@zackm0571  Yes, I have released the camera on pause. But the question is - Either WhatsApp released camera or just unbuplishVideoTrack in background.

**Here is code that I used in OnPause**

    @Override
    protected void onPause() {
        /*
         * Release the local video track before going in the background. This ensures that the
         * camera can be used by other applications while this app is in the background.
         */
        if (localVideoTrack != null) {
            /*
             * If this local video track is being shared in a Room, unpublish from room before
             * releasing the video track. Participants will be notified that the track has been
             * unpublished.
             */
            if (localParticipant != null) {
                localParticipant.unpublishTrack(localVideoTrack);
            }

            localVideoTrack.release();
            localVideoTrack = null;
        }
        super.onPause();
    }

**Comment by zackm0571** [comment]
Hey @MukFlex thanks for showing your `onPause` code.  Just a couple more questions as I troubleshoot on my end:

- Does this happen on more devices than just the Samsung J2? 
- What OS version is the Samsung J2?
- What version of the Video Android SDK are you using?

Thanks :)

**Comment by zackm0571** [comment]
Hey @MukFlex I'm going to close this one for now. Please re-open another issue if you're continuing to face the same problem. :)
