### ISSUE TITLE
Samsung S10 experiences crash when joining a room or when switching cameras 

### ISSUE THREAD

**Issue by zackm0571** [twilio/video-quickstart-android#431]
Certain Samsung S10 models are currently crashing when switching cameras or joining a room. These models contain more than two cameras and we are currently working to update our SDK to handle this use case.  

### Description
Apps that consume video by Twilio and run on a Samsung S10 will experience a hard crash crash when switching the camera or joining a room.

### Effected models
- `SM-G977U`

### Steps to Reproduce

1. Install quickStart on Samsung S10
2. Switch the camera or join a room
3. Crash

### Stacktrace
```
2019-08-13 11:15:00.134 25745-26091/com.twilio.video.app.internal.debug E/AndroidRuntime: FATAL EXCEPTION: Camera SurfaceTextureHelper
    Process: com.twilio.video.app.internal.debug, PID: 25745
    java.lang.IllegalArgumentException: format not available
        at android.hardware.camera2.params.StreamConfigurationMap.getInternalFormatSizes(StreamConfigurationMap.java:1286)
        at android.hardware.camera2.params.StreamConfigurationMap.getOutputSizes(StreamConfigurationMap.java:460)
        at org.webrtc.Camera2Enumerator.getSupportedSizes(Camera2Enumerator.java:145)
        at org.webrtc.Camera2Session.findCaptureFormat(Camera2Session.java:355)
        at org.webrtc.Camera2Session.start(Camera2Session.java:343)
        at org.webrtc.Camera2Session.<init>(Camera2Session.java:326)
        at org.webrtc.Camera2Session.create(Camera2Session.java:302)
        at org.webrtc.Camera2Capturer.createCameraSession(Camera2Capturer.java:36)
        at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:306)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Workaround

#432 contains a temporary fix in `CameraCapturerCompat` which checks that a camera supports `ImageFormat.PRIVATE` before allowing the camera to be used as a capture device. This will prevent the crash. 

### Fix

- We are actively working on a more long term solution and will update this issue as we move forward.

**Comment by aaalaniz** [comment]
I believe the workaround provided in #432 should suffice to close this issue.
