### ISSUE TITLE
FATAL EXCEPTION: main Process: com.twilio.video.quickstart, PID: 7349

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-android#441]
Hi there,

I've downloaded Twilio's **video-quickstart-android-master**, and I've migrated the **quickstart** app to [androidx](https://developer.android.com/jetpack/androidx/migrate) as I was facing duplicate library issues (see below) after adding this dependency (_implementation 'com.google.firebase:firebase-analytics:17.2.0'_) to app's gradle file on Android Studio 3.5.

**Duplicate Library Issues**
```
Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.IResultReceiver found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.IResultReceiver$Stub found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.IResultReceiver$Stub$Proxy found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.ResultReceiver found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.ResultReceiver$1 found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.ResultReceiver$MyResultReceiver found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
```

To overcome the _Duplicate Library Issues_  I've migrated to androidx.

After i've migrated to androidx, I've tried to run the app and got the below errors:

Steps to reproduce the error:
1. Migrate the Twilio video quickstart app to androidx 
2. Run the app on virtual device (Pixel 2) using Android studio 3.5 

**Error Logs**
```
2019-09-24 17:55:16.497 7349-7349/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.twilio.video.quickstart, PID: 7349
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twilio.video.quickstart/com.twilio.video.quickstart.activity.VideoActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/com.twilio.video.quickstart-Xxwt8bYtb6dvh5F6MOWSSA==/base.apk"],nativeLibraryDirectories=[/data/app/com.twilio.video.quickstart-Xxwt8bYtb6dvh5F6MOWSSA==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.twilio.video.quickstart.activity.VideoActivity.onCreate(VideoActivity.java:165)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

2019-09-24 17:55:31.388 6200-6241/? E/anmb: Phenotype API error. Event # bywv@85839934, EventCode: 12 [CONTEXT service_id=51 ]
    ankz: 29503
        at anmh.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):25)
        at anmb.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):90)
        at anmb.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):73)
        at zvv.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):17)
        at bkgy.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
        at sjm.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):33)
        at sjm.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at spf.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-09-24 17:55:31.389 6200-6241/? E/AsyncOperation: serviceID=51, operation=GetCommittedConfigurationOperationCall
    OperationException[Status{statusCode=unknown status code: 29503, resolution=null}]
        at anmb.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):98)
        at anmb.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):73)
        at zvv.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):17)
        at bkgy.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
        at sjm.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):33)
        at sjm.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at spf.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-09-24 17:55:31.390 6200-6227/? E/NetRec: [395] akgk.a: Could not retrieve server token for package com.google.android.apps.gcs
    java.util.concurrent.ExecutionException: rcv: 29503: 
        at aumz.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):4)
        at aumz.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):20)
        at akgk.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):1)
        at akgk.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):4)
        at akgf.getHeaders(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
        at com.android.volley.toolbox.HttpClientStack.performRequest(:com.google.android.gms@19275040@19.2.75 (100700-269183835):9)
        at scm.performRequest(:com.google.android.gms@19275040@19.2.75 (100700-269183835):1)
        at bsq.executeRequest(:com.google.android.gms@19275040@19.2.75 (100700-269183835):1)
        at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms@19275040@19.2.75 (100700-269183835):5)
        at scl.performRequest(:com.google.android.gms@19275040@19.2.75 (100700-269183835):13)
        at com.android.volley.NetworkDispatcher.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):7)
        at com.android.volley.NetworkDispatcher.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
     Caused by: rcv: 29503: 
        at rir.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):4)
        at anjx.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
        at anmh.a(:com.google.android.gms@19275040@19.2.75 (100700-269183835):6)
        at zvv.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):27)
        at bkgy.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):2)
        at sjm.b(:com.google.android.gms@19275040@19.2.75 (100700-269183835):33)
        at sjm.run(:com.google.android.gms@19275040@19.2.75 (100700-269183835):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at spf.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by aaalaniz** [comment]
Hey @pranavdesh 

I looked at the stack trace and this doesn't appear to be an issue with the Video Android SDK or the quickstart. We do intend to stay up-to-date with the latest libraries, so we will eventually migrate to Android X. I will close this issue for now.

Thank you

**Comment by a1nouru** [comment]
If you upgrade to AndroidX. 

I am assuming you solved this already but for the next person, they can Go to `Refactor` then `Migrate to AndroidX` that should solve it.
