### ISSUE TITLE
Exception from call site #51 bootstrap method

### ISSUE THREAD

**Issue by vinayappypiellp** [twilio/video-quickstart-android#460]
face this issue while creating room.

    Process: com.practise.twiliochatdemo, PID: 27787
    java.lang.BootstrapMethodError: Exception from call site #51 bootstrap method
        at com.twilio.video.Room.<init>(Room.java:230)
        at com.twilio.video.Video.connect(Video.java:137)
        at com.practise.twiliochatdemo.callfeature.CallActivity.connect(CallActivity.kt:60)
        at com.practise.twiliochatdemo.callfeature.CallActivity.onCreate(CallActivity.kt:30)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)

**Comment by aaalaniz** [comment]
Hey @vinayappypiellp 

Does your application target Java 8? Beginning with Video Android SDK 3.x+, applications are required to target Java 8. Reference the quickstart examples or the [Android developer documentation](https://developer.android.com/studio/write/java8-support).

Thank you
