### ISSUE TITLE
Cannot load library if library failed to load previously

### ISSUE THREAD

**Issue by aaalaniz** [twilio/video-quickstart-android#53]
On some older devices there appears to be a problem loading the native library. The issue appears to be related to [this bug](https://code.google.com/p/android/issues/detail?id=73725) and could be solved when we upgrade to NDK r13. We will maintain a table of known affected devices for reference. Please feel free to comment with affected devices and I will update the following table.

| Device | Android Version |
| ------- | ---------------- |
| Sony Xperia S | 4.1.2 |
| SH-06E | 4.2.2 |

Here is the stacktrace.

```
java.lang.UnsatisfiedLinkError: Cannot load library: find_library[1201]:   154 'libjingle_peerconnection_so.so' failed to load previously
        at java.lang.Runtime.load(Runtime.java:340)
        at java.lang.System.load(System.java:521)
        at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at com.twilio.video.MediaFactory.instance(MediaFactory.java:27)
        at com.twilio.video.LocalMedia.create(LocalMedia.java:38)
```

**Comment by wildstarzw** [comment]
Hi
I tested with virtual devices, and it seems only happen at the device which is under API 18. 
Hope it helps.

**Comment by idelgado** [comment]
This seems to be the specific issue we are encountering https://github.com/KeepSafe/ReLinker/issues/15

And it looks like there is a fix for this in the ndk project https://github.com/android-ndk/ndk/issues/113

**Comment by TheChuckster** [comment]
Hi, I'm one of those persistent buggers from the other issues!

If it helps, it looks like the real fix is that you'll need to recompile libjingle_peerconnection_so.so against the latest NDK (while targeting a lower API level) -- of course, compiling WebRTC using Google's esoteric build system is about as fun as getting a root canal, but in the end, it worked fine for us.

**Comment by idelgado** [comment]
@TheChuckster thanks for the info.

We believe we solved the issue by setting `-DANDROID_PLATFORM=android-16` instead of `-DANDROID_PLATFORM=android-21` in our gradle ndk build.

We should have a release with this fix very soon.
