### ISSUE TITLE
App crash on Samsung S5e Android 9.0

### ISSUE THREAD

**Issue by hemaidbizspice** [twilio/video-quickstart-android#580]
### Description
When the user starts connecting to the room, the app crash and gives this exception 

### Steps to Reproduce
1- open the room screen
2. click on the join button

#### Expected Behavior

Should be able to join the meeting

#### Actual Behavior

The app crash 

#### Reproduces how Often

100% on Samsung S5e Android 9.0

#### Logs

  
    E/tvi.webrtc.Logging: Camera2Session: Error: Camera device could not be opened due to a device policy.

    I/tvi.webrtc.Logging: Camera2Session: Stop internal

    SurfaceTextureHelper: stopListening()

    D/ClearFromRecentService: Service Destroyed

    E/CameraCaptureSession: Session 0: Exception while stopping repeating:

    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2435)

        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1126)

        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)

        at tvi.webrtc.Camera2Session.stopInternal(Camera2Session.java:408)

        at tvi.webrtc.Camera2Session.reportError(Camera2Session.java:429)

        at tvi.webrtc.Camera2Session.access$600(Camera2Session.java:37)

        at tvi.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:117)

        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:1929)

        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)

        at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)

        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:258)

        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)

        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)

        at android.os.Handler.handleCallback(Handler.java:873)

        at android.os.Handler.dispatchMessage(Handler.java:99)

        at android.os.Looper.loop(Looper.java:214)

        at android.os.HandlerThread.run(HandlerThread.java:65)

I/CameraManagerGlobal: postSingleUpdate device: camera id 1 status STATUS_PRESENT`

### Versions

All relevant version information for issue.

#### Video Android SDK
5.13.0

#### Android API

28

#### Android Device

Samsung S5e

**Comment by aaalaniz** [comment]
Hey @hemaidbizspice 

This error appears to be occuring as a result of the [device specific policy](https://developer.android.com/reference/android/hardware/camera2/CameraDevice.StateCallback#ERROR_CAMERA_DISABLED).

Do you see this error on other devices?

Thanks!

**Comment by hemaidbizspice** [comment]
Thank you for your reply!

Yeah, but I don't know how to handle this with Twilio, the problem solved on the latest twilio-video-app repo, but I am using an old code and architecture, it's very hard to track the issue with the new implementation.

No, I have tested it on more than 10 devices and I didn't face the issue.

Also, the issue starts when the user connects to the room on:
`
    private fun addParticipantViews() {
        if (room != null && localParticipant != null) {
            localParticipantSid = localParticipant!!.sid
            // remove primary view
            participantController.removePrimary()
`
on removePrimary()  the primaryItem var in ParticipantController returns null on that device.

Thank you!

**Comment by mohammedhemaid** [comment]
after days of debugging, we found that it's an issue with the Twilio chat on 3.1.1 just updated it to the latest version and now everything is working

**Comment by aaalaniz** [comment]
Hey @mohammedhemaid 

I'm glad you were able to resolve the issue. Can you provide more details about the issue? Is the issue something we should document to users of Programmable Video and Programmable Chat?

Thanks!

**Comment by mohammedhemaid** [comment]
It was giving this error (trying to load twilio-rtd-native), I found an issue on chat repo 
https://github.com/twilio/twilio-chat-demo-android/issues/67
that solution was to upgrade the chat library, but we stopped supporting pre-lollipop devices.
