### ISSUE TITLE
exampleCustomVideoSink - IndexOutOfBoundsException with Camera2Capturer

### ISSUE THREAD

**Issue by cyodrew** [twilio/video-quickstart-android#592]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

The custom video sink example `exampleCustomVideoSink` utilizes the `Camera1Enumerator` to find a camera ID for use with a `CameraCapturer`. When attempting to capture the Bitmap for a snapshot, the frame buffer `VideoFrame.Buffer` is determined to be a `VideoFrame.I420Buffer`. If the user swaps out the `Camera1Enumerator` and `CameraCapturer` with a `Camera2Enumerator` and `Camera2Capturer`, the frame buffer is determined to be a `VideoFrame.TextureBuffer`. However, during the conversion process, an `IndexOutOfBoundException` is thrown in the `fastI420ToYuvImage` function. It appears that the `yuvPlanes[0].get` function is getting an index in the loop that is out of its bounds. My guess is something to do with the rotation.

```
for (row in 0 until height) {
        for (col in 0 until width) {
            bytes[i++] = yuvPlanes[0].get(col + row * yuvStrides[0])
        }
    }
```

### Steps to Reproduce

1. Swap `Camera1Enumerator` for `Camera2Enumerator` when determining the `frontCameraId`
2. Change `CameraCapturer` to `Camera2Capturer` when creating the `localVideoTrack`
3. Run the app
4. Tap the video to produce a screenshot
5. The `IndexOutOfBoundsException` is thrown

#### Code

```kotlin
// Code that help reproduce the issue
private val frontCameraId by lazy {
        val camera2Enumerator = Camera2Enumerator()
        val cameraId = camera2Enumerator.deviceNames.find { camera2Enumerator.isFrontFacing(it) }
        requireNotNull(cameraId)
    }
private val localVideoTrack by lazy {
       LocalVideoTrack.create(
           this, true, Camera2Capturer(
               this,
               frontCameraId, null
            )
        )
    }
```

#### Expected Behavior

The conversion process from should produce a `YuvImage` correctly in the process of generating the snapshot

#### Actual Behavior

The app crashes with an `IndexOutOfBoundsException` as a `System.err`

#### Reproduces how Often

100%

#### Logs

```
// Log output when issue occurs
W/System.err: java.lang.IndexOutOfBoundsException: index=307200 out of bounds (limit=307200)
        at java.nio.Buffer.checkIndex(Buffer.java:556)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:224)
        at com.twilio.video.examples.common.VideoFrameKtxKt.fastI420ToYuvImage(VideoFrameKtx.kt:151)
        at com.twilio.video.examples.common.VideoFrameKtxKt.i420ToYuvImage(VideoFrameKtx.kt:112)
        at com.twilio.video.examples.common.VideoFrameKtxKt.captureBitmapFromTexture(VideoFrameKtx.kt:75)
        at com.twilio.video.examples.common.VideoFrameKtxKt.captureBitmap(VideoFrameKtx.kt:27)
        at com.twilio.video.examples.common.VideoFrameKtxKt.toBitmap(VideoFrameKtx.kt:23)
        at com.twilio.video.examples.customvideosink.SnapshotVideoSink.onFrame(SnapshotVideoSink.kt:24)
        at tvi.webrtc.NativeAndroidVideoTrackSource.nativeOnFrameCaptured(Native Method)
        at tvi.webrtc.NativeAndroidVideoTrackSource.onFrameCaptured(NativeAndroidVideoTrackSource.java:58)
        at tvi.webrtc.VideoSource$1.onFrameCaptured(VideoSource.java:73)
        at tvi.webrtc.CameraCapturer$2.onFrameCaptured(CameraCapturer.java:167)
W/System.err:     at tvi.webrtc.Camera2Session$CaptureSessionCallback.lambda$onConfigured$0$Camera2Session$CaptureSessionCallback(Camera2Session.java:186)
        at tvi.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$avOpmBlgtFuwVDip8hBflrg29nE.onFrame(Unknown Source:2)
        at tvi.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:369)
        at tvi.webrtc.SurfaceTextureHelper.lambda$new$0$SurfaceTextureHelper(SurfaceTextureHelper.java:203)
        at tvi.webrtc.-$$Lambda$SurfaceTextureHelper$EKW8Jd6axgVjWfpHIgbbTEnvOGQ.onFrameAvailable(Unknown Source:2)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/rtc: #
    # Fatal error in: gen/sdk/android/generated_base_jni/../../../../../../../src/sdk/android/src/jni/jni_generator_helper.h, line 94
    # last system error: 0
    # Check failed: !env->ExceptionCheck()
    # 
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1042 (CaptureThread), pid 753 (.customrenderer)
```

### Versions

All relevant version information for issue.

#### Video Android SDK

6.0.0

#### Android API

30

#### Android Device

Pixel 3a

**Comment by aaalaniz** [comment]
Hey @cyodrew 

Thanks for opening the issue! I will take a look and get back to you!
