### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service

### ISSUE THREAD

**Issue by khangdm** [twilio/video-quickstart-android#601]
### Description
App crashes due to the following error log. It did not crash before beta 5 version.
### Steps to Reproduce

1.Steps to Reproduce
2.App crashes when local camera stream is created.
#### Expected Behavior
App should not crash
#### Actual Behavior
App crash
#### Reproduces how Often
100%
#### Logs

```
Caused by: java.lang.IllegalStateException: Supported formats could not be retrieved because an error occurred connecting to the camera service
        at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
        at com.twilio.video.CameraCapturer.getSupportedFormats(CameraCapturer.java:341)
        at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:165)
        at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:100)
        at com.newbees.streamer.twilio.TwilioManager.createVideoTrack(TwilioManager.java:153)
        at com.newbees.streamer.twilio.TwilioManager.createAudioAndVideoTracks(TwilioManager.java:143)
        at com.newbees.streamer.twilio.VideoCallManager.config(VideoCallManager.java:153)
        at com.newbees.streamer.twilio.VideoCallManager.<init>(VideoCallManager.java:95)
        at com.newbees.streamer.videocall.VideoCallActivity$1.permissionCallback(VideoCallActivity.java:82)
        at com.newbees.streamer.base.BaseActivity.checkPermissions(BaseActivity.java:73)
        at com.newbees.streamer.videocall.VideoCallActivity.init(VideoCallActivity.java:100)
        at com.newbees.streamer.base.BaseActivity.onCreate(BaseActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:6085)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
        at android.app.ActivityThread.access$900(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5408) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) ```

### Versions

#### Video Android SDK
Video Android SDK
5.0.1
#### Android API
21-30
#### Android Device
oppo a51w, samsung note8

**Comment by Alton09** [comment]
Hi @khangdm. Can you try utilizing the [CameraCapturerCompat](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt) class to instantiate the camera capturer? This may help filter out the unsupported format this error is reporting. If you app is in Java, you can use this [CameraCapturerCompat](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java) from the quickstart. Thanks!

**Comment by Alton09** [comment]
Hi @khangdm . Just checking in regarding this issue. Did using the compat class above solve the problem?

**Comment by khangdm** [comment]
hi @ Alton09 alto. Sorry I'm late. I used CameraCapturerCompat and the required twilio version is 6.x. But now I am using twilio5.x version. Can I use CameraCapturerCompat in version 5.x. Thank you

**Comment by khangdm** [comment]
hi @Alton09 i'm processed bitmap using opencv now. but how this frame going to reflect on videoview? .Should i convert bitmap to VideoFrame? or how do i pass VideoFrame back to render ?
