### ISSUE TITLE
Help wanted: Can't create camera capturers.

### ISSUE THREAD

**Issue by VanKhulup** [twilio/video-quickstart-android#603]
Greetings! I've recently got quite a few crashes from the production version of the app because the app could not create camera capturers. I'm using [CameraCapturerCompat](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt) class from Twilio Video App to select appropriate CameraCapturer implementation. But it seems like few devices can't start image capturing. The range of affected OS versions is 7.0 - 10, and the affected devices are different.
![image](https://user-images.githubusercontent.com/49081243/103288769-57433b00-49ee-11eb-9123-7809da7eb6da.png)
Unfortunately, I don't have access to any of these devices, and my own test devices don't have this issue. I've managed to get this crash reproduced by removing the check for PRIVATE image format within [isCameraSupported](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt#L104) method within CameraCapturerCompat. So my guess is that few devices that might not support this image format.

So my question is this - what is the reasoning, from SDK's point of view, to have this check?

**Comment by Alton09** [comment]
Hi @VanKhulup! Thank you for reaching out. Is there a stack trace from the devices that reported the crash? Sharing this will help us further troubleshoot this issue. Thanks!

**Comment by Alton09** [comment]
Also, what version of the SDK are you using?

**Comment by VanKhulup** [comment]
I'm using SDK version 6.0.0. I think the stack trace won't tell much - it's just plain viewModel initialization flow.
``` kotlin
 java.lang.IllegalArgumentException: could not create neither Camera2 nor Camera1 capturers
at private.TwilioPublishingViewModel.<init>(TwilioPublishingViewModel.kt:36)
at private.video.core.generic.THViewModelProvider.create(THViewModelProvider.kt:35)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
```
The crash itself is cause when the following method fails to create capturer, and so returns null:
```kotlin
fun newInstance(context: Context): CameraCapturerCompat? {
            return if (Camera2Capturer.isSupported(context)) {
                Camera2Enumerator(context).getFrontAndBackCameraIds(context)?.let { cameraIds ->
                    val cameraCapturer = Camera2Capturer(context, cameraIds.first
                            ?: cameraIds.second ?: "")
                    CameraCapturerCompat(cameraIds.first, cameraIds.second, camera2Capturer = cameraCapturer)
                }
            } else {
                Camera1Enumerator().getFrontAndBackCameraIds(context)?.let { cameraIds ->
                    val cameraCapturer = CameraCapturer(context, cameraIds.first ?: cameraIds.second
                    ?: "")
                    CameraCapturerCompat(cameraIds.first, cameraIds.second, cameraCapturer = cameraCapturer)
                }
            }
        }
```

**Comment by VanKhulup** [comment]
This devices on SDK version 5.12.0 was crashing with following stack trace:
```kotlin
java.lang.IllegalStateException: Camera2Capturer is not supported on this device
        at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
        at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:233)
        at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:217)
        at private.session.participant.twilio.TwilioPublishingViewModel.initCameraCapturer(TwilioPublishingViewModel.kt:201)
```
This issue actually forced me to try and go with CameraCapturerCompat implementation

**Comment by Alton09** [comment]
Thanks for the additional information @VanKhulup. The function could be returning null if the cameras on the device do not meet the conditions defined in the `isCameraIdSupported` function. Do you have any additional details on which exact devices this crash is occurring on? I can try running instrumentation tests against this class in Firebase Test Lab against an array of devices to see if I can reproduce it in the meantime.

**Comment by VanKhulup** [comment]
![image](https://user-images.githubusercontent.com/49081243/103707823-061be400-4fb8-11eb-8f3f-bf00e997c4a7.png)
![image](https://user-images.githubusercontent.com/49081243/103707844-13d16980-4fb8-11eb-848b-cdb902da8576.png)
![image](https://user-images.githubusercontent.com/49081243/103707918-36fc1900-4fb8-11eb-8c4e-05d04cff26f2.png)


these are top affected devices/manufacturers/OS versions

**Comment by Alton09** [comment]
Thank you for sharing this info @VanKhulup. I'll troubleshoot further with FTL to see if I can reproduce this issue.
