### ISSUE TITLE
crash when convert VideoFrame remote video to bitmap.

### ISSUE THREAD

**Issue by khangdm** [twilio/video-quickstart-android#613]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description
crash when convert VideoFrame remote video to bitmap.

### Steps to Reproduce

1. Using google pixel 3xl as a local participant. Remote participant is Samsung note 8
2. Make a call
3. Crash when start convert VideoFrame remote to Bitmap

#### Code

```java
fun toBitmap(videoFrame: VideoFrame) : Bitmap? {
    val i420Buffer = if (videoFrame.buffer is VideoFrame.TextureBuffer) {
        val yuvConverter = YuvConverter()
        val buffer = yuvConverter.convert(videoFrame.buffer as VideoFrame.TextureBuffer)
        yuvConverter.release()
        buffer
    } else {
        videoFrame.buffer.toI420()
    }
    val yuvImage = i420ToYuvImage(
            i420Buffer,
            videoFrame.buffer.width,
            videoFrame.buffer.height
    )
    val stream = ByteArrayOutputStream()
    val rect =
            Rect(0, 0, yuvImage.width, yuvImage.height)

    // Compress YuvImage to jpeg
    yuvImage.compressToJpeg(rect, 100, stream)

    // Convert jpeg to Bitmap
    val imageBytes = stream.toByteArray()
    var bitmap = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        val buffer = ByteBuffer.wrap(imageBytes)
        val src =
                ImageDecoder.createSource(buffer)
        try {
            ImageDecoder.decodeBitmap(src)
        } catch (e: IOException) {
            e.printStackTrace()
            return null
        }
    } else {
        BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
    }
    val matrix = Matrix()

    // Apply any needed rotation
    matrix.postRotate(videoFrame.rotation.toFloat())
    bitmap = Bitmap.createBitmap(
            bitmap!!, 0, 0, bitmap.width, bitmap.height, matrix, true
    )
    return bitmap
}
```

#### Expected Behavior
crash when convert VideoFrame remote to Bitmap

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
W/System.err: java.lang.IllegalStateException: Framebuffer not complete, status: 0
        at tvi.webrtc.GlTextureFrameBuffer.setSize(GlTextureFrameBuffer.java:86)
        at tvi.webrtc.YuvConverter.convert(YuvConverter.java:176)
        at com.newbees.streamer.image_service.VideoFrameKtxKt.toBitmap(VideoFrameKtx.kt:24)
        at com.newbees.streamer.twilio.VideoTextureViewRenderer.i420FrameToBitmap(VideoTextureViewRenderer.java:316)
        at com.newbees.streamer.twilio.VideoTextureViewRenderer.virtualBackground(VideoTextureViewRenderer.java:241)
        at com.newbees.streamer.twilio.VideoTextureViewRenderer.createVirtualBackgroundBitmap(VideoTextureViewRenderer.java:176)
        at com.newbees.streamer.twilio.VideoTextureViewRenderer.onFrame(VideoTextureViewRenderer.java:145)
E/rtc: #
```

### Versions

All relevant version information for issue.

#### Video Android SDK

6.1.0

#### Android API
Android target API 29
#### Android Device
SamSung note 8
google pixel 3xl

**Comment by Alton09** [comment]
Hi @khangdm. Thanks for reaching out regarding this issue. Are you running this example directly from the video-quickstart project or you referencing this class from your own application? Thanks.

**Comment by khangdm** [comment]
Hi @ Alton09. Thanks for answering. I refer this class from my own application. I tried converting the VideoFrame of the remote video to a bitmap but it failed. But when working with local video, it's perfect.

**Comment by Alton09** [comment]
Thanks for the additional info @khangdm . I'll add a story to our backlog to investigate this issue and troubleshoot further.

**Comment by khangdm** [comment]
hi @Alton09 thank you for supporting. Hope you update the issue in the future

**Comment by afalls-twilio** [comment]
@khangdm Sorry for the late response, is this still an issue with more recent releases (try 7.3.x+)?

**Comment by karansandhu** [comment]
Hello @khangdm  did you find the solution as i am also facing the exact problem.
@Alton09 did you find?

@afalls-twilio already running version 7.3+ please help me i am facing a major problem.

**Comment by afalls-twilio** [comment]
@karansandhu Sorry about the late response. The code here all uses internal WebRTC APIs, and we are in the midst of a significant release were we are upgrading to a much more recent version of WebRTC. After the release, we hope to investigate this if its still an issue. I have filed a ticket to keep track of it.

**Comment by ocarevs** [comment]
Hi @khangdm it appears that opengl context is not initialised in case of the remote track. Calls to GLES methods produce `call to OpenGL ES API with no current context` within that scope. What I suggest is just using the `videoFrame.buffer.toI420()` that's in the else statement to convert the `buffer` and remote the `YuvConverter()` part, it works perfectly fine.
