### ISSUE TITLE
Alternating spamming of flash toggling and camera switching crashes the app (Camera2Capturer)

### ISSUE THREAD

**Issue by marqroldan** [twilio/video-quickstart-android#631]
### Description

Basically the title..

### Steps to Reproduce

1. Make sure there's a working preview of your camera
2. Spam alternatively the toggling of flash and switching of camera

#### Code

```java

//// ====== camera capturer ===================================


                camera2Capturer = new Camera2Capturer(context, camera2IdMap.get(cameraSource),
                        new Camera2Capturer.Listener() {
                            @Override
                            public void onFirstFrameAvailable() {
                            }

                            @Override
                            public void onCameraSwitched(String newCameraId) {
                                onCameraSwitchedEvent();
                            }

                            @Override
                            public void onError(Camera2Capturer.Exception camera2CapturerException) {
                                Log.i(TAG, "capturerCompat-Camera2Capturer message: " + camera2CapturerException.getMessage());
                                Log.i(TAG, "capturerCompat-Camera2Capturer: Code = " + Integer.toString(camera2CapturerException.getCode()));
                            }
                        });


//// ====== switchCamera ===================================
                    camera2Capturer.switchCamera(newCameraId);

//// ====== toggleFlash ===================================
                CameraCharacteristics cameraCharacteristics;
                cameraCharacteristics = getCameraCharacteristics(camera2Capturer.getCameraId());
                if (isCameraWithFlashFound && cameraCharacteristics != null && cameraCharacteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE)) {
                    camera2Capturer.updateCaptureRequest(new CaptureRequestUpdater() {
                        @Override
                        public void apply(@NonNull CaptureRequest.Builder captureRequestBuilder) {
                            if (isFlashOn) {
                                captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_OFF);
                                captureRequestBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_OFF);
                                isFlashOn = false;
                            } else {
                                captureRequestBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON);
                                captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_TORCH);
                                isFlashOn = true;
                            }
                            toggleFlashSuccess(isFlashOn);
                        }
                    });
                }

```

#### Expected Behavior

Exceptions should be forwarded to the listener

#### Actual Behavior

Crashes the app

#### Reproduces how Often

All of the time

#### Logs

```
	12:35:37.725	AndroidRuntime		FATAL EXCEPTION: CaptureThread
Process: com.my.app, PID: 4093
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
	at tvi.webrtc.Camera2Session.configureCaptureRequestBuilder(Camera2Session.java:369)
	at com.twilio.video.Camera2Capturer.updateCaptureRequestOnCameraThread(Camera2Capturer.java:439)
	at com.twilio.video.Camera2Capturer.lambda$updateCaptureRequest$1$Camera2Capturer(Camera2Capturer.java:391)
	at com.twilio.video.-$$Lambda$Camera2Capturer$CcvEP_UV-5a3qu8wTCCcc6bukzY.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Versions

All relevant version information for issue.

#### Video Android SDK

6.2.1

#### Android API

11

#### Android Device

SM-A715F

--------------------------

I'm actually not sure if I'm doing it correctly, should I be saving a state before/after switching the camera before allowing the toggling of the flash? Either way I think it should go inside Camera2.Listener's onError

**Comment by Alton09** [comment]
Hi @marqroldan! Thanks for reaching out regarding this issue. We'll try to take a deeper look into this one soon to provide further guidance.

**Comment by dod-sgallese** [comment]
I also noticed a crash occurs even if waiting until onCameraSwitched completes and then trying to toggle flash.

**Comment by afalls-twilio** [comment]
@marqroldan @dod-sgallese This issue should be fixed in the next release
