### ISSUE TITLE
UnsatisfiedLinkError when using JavaI420Buffer (Kotlin)

### ISSUE THREAD

**Issue by jeryini** [twilio/video-quickstart-android#643]
### Description
When trying to allocate JavaI420Buffer via the following call:
```
tvi.webrtc.JavaI420Buffer.allocate(width, height)
```
I get the following error:
```
java.lang.UnsatisfiedLinkError: No implementation found for java.nio.ByteBuffer tvi.webrtc.JniCommon.nativeAllocateByteBuffer(int) (tried Java_tvi_webrtc_JniCommon_nativeAllocateByteBuffer and Java_tvi_webrtc_JniCommon_nativeAllocateByteBuffer__I)
        at tvi.webrtc.JniCommon.nativeAllocateByteBuffer(Native Method)
        at tvi.webrtc.JavaI420Buffer.allocate(JavaI420Buffer.java:87)
        at dji.ux.beta.core.widget.fpv.FPVWidget$onSurfaceTextureAvailable$yuvDataListener$1.onYuvDataReceived(FPVWidget.kt:417)
```

Before this error I also get:
```
2021-05-28 08:31:27.367 15131-15131/? I/tvi.webrtc.Logging: NativeLibrary: Loading native library: jingle_peerconnection_so
2021-05-28 08:31:27.367 15131-15131/? I/tvi.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
2021-05-28 08:31:27.369 15131-15131/? E/tvi.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
2021-05-28 08:31:27.369 15131-15131/? E/tvi.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjingle_peerconnection_so.so" not found
2021-05-28 08:31:27.370 15131-15131/? E/tvi.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjingle_peerconnection_so.so" not found
```

Strangely if I declare to use official org.webrtc library (`implementation 'org.webrtc:google-webrtc:1.0.32006'`) then native call to allocate byte buffer succeeds.

### Video Android SDK Version

`com.twilio:video-android-ktx:6.3.0`

**Comment by jeryini** [comment]
Any thoughts here? If it's working fine for `org.webrtc` call, then this might mean it's a library issue when used from Kotlin?

**Comment by jeryini** [comment]
Just found out that I have the same issue also when using `org.webrtc` library. Discovered that I need to run the following code to avoid having these issues:
```
org.webrtc.PeerConnectionFactory.initialize(org.webrtc.PeerConnectionFactory.InitializationOptions
                        .builder(context)
                        .createInitializationOptions())
                val rootEglBase = org.webrtc.EglBase.create()
                val peerConnectionFactory = org.webrtc.PeerConnectionFactory.builder()
                        .setVideoDecoderFactory(org.webrtc.DefaultVideoDecoderFactory(rootEglBase.getEglBaseContext()))
                        .setVideoEncoderFactory(org.webrtc.DefaultVideoEncoderFactory(rootEglBase.getEglBaseContext(), true, true))
                        .createPeerConnectionFactory()
```
If I instead use `tvi.webrtc`, I still get the following issue (doesn't happen when using `org.webrtc`):
```
java.lang.UnsatisfiedLinkError: No implementation found for void tvi.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_tvi_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_tvi_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
```

**Comment by jeryini** [comment]
Strange, tried moving this part of the initialize call to Java class, still getting:
```
I/tvi.webrtc.Logging: NativeLibrary: Loading native library: jingle_peerconnection_so
    NativeLibrary: Loading library: jingle_peerconnection_so
E/.ux.beta.sampl: No implementation found for void tvi.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_tvi_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_tvi_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
```
But native library is actually being loaded, as per log above: `Loading native library: jingle_peerconnection_so`

**Comment by jeryini** [comment]
Hello!

Has anyone managed to look into this issue? I would be glad to provide any additional details if required.

Cheers,
Jernej

**Comment by jeryini** [comment]
Actually found out that I was missing the following call:
```
ReLinker.loadLibrary(context, com.twilio.video.BuildConfig.TWILIO_VIDEO_ANDROID_LIBRARY);
```
or just native load library one:
```
System.loadLibrary(com.twilio.video.BuildConfig.TWILIO_VIDEO_ANDROID_LIBRARY)
```
