### ISSUE TITLE
Can't capture camera on Samsung J8 - Camera name 1 does not match any known camera device.

### ISSUE THREAD

**Issue by mertkokusen** [twilio/video-quickstart-android#659]
Hello, 

We have received couple of complaint from our users recently. They can't connect to calls on some devices. Here is our crash logs we acquired from crashlytics.

So far this exception only been thrown on following models: Samsuns J7 Max, Samsung J8, GAlaxy Note and  Xiaomi MiA2

Not sure if this is a genuine bug or we are  using the sdk wrong. But same code is working on several other devices.

```
Fatal Exception: java.lang.IllegalArgumentException: Camera name 1 does not match any known camera device.
       at tvi.webrtc.CameraCapturer.<init>(CameraCapturer.java:230)
       at tvi.webrtc.Camera1Capturer.<init>(Camera1Capturer.java:20)
       at tvi.webrtc.Camera1Enumerator.createCapturer(Camera1Enumerator.java:74)
       at com.twilio.video.CameraCapturer.initialize(CameraCapturer.java:272)
       at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:184)
       at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:141)
       at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:92)
       at com.*****.call.video.TwilioVideoCallPresenter.initVideoStreamConnection(TwilioVideoCallPresenter.java:151)
       at com.*****.call.video.VideoCallPresenter.checkAndRequestPermissionIfNotGranted(VideoCallPresenter.java:188)
       at com.*****.call.video.VideoCallPresenter.onViewAttached(VideoCallPresenter.java:31)
       at com.*****.core.base.presenter.BasePresenterImpl.onViewAttached(BasePresenterImpl.java:45)
       at com.*****.core.base.presenter.BasePresenterImpl.onViewAttached(BasePresenterImpl.java:32)
       at com.*****.core.base.view.BaseActivity.doAttach(BaseActivity.java:156)
       at com.*****.core.base.view.BaseActivity.access$getNEED_TO_SAVE_STATE$cp(BaseActivity.java:48)
       at com.*****.core.base.view.BaseActivity$onLoadFinished$1.run(BaseActivity.java:198)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by amaan118921** [comment]
any update?

**Comment by xhozst** [comment]
I have the same issue on my Pixel 6.

**Comment by xhozst** [comment]
I was able to resolve by using Camera2Capturer instead of CameraCapturer in my Xamarin Project when creating the LocalVideoTrack.

**Comment by afalls-twilio** [comment]
@xhozst @amaan118921  Thank you for the bug report. I tested with a Galaxy Note (SM-N950N) and was unable to reproduce it. I am guessing that certain devices have something different in regards to their naming or that their camera/info objects are null (which would be an OEM bug). 

There is a class (its not public), called Camera1Enumerator.class, I was wondering if you could construct it and call getDeviceNames and print out what it reports...


```
Camera1Enumerator c1e = new Camera1Enumerator();
for (String name : c1e.getDeviceNames()) {
   Log.d(TAG, name)
}
```

**Comment by afalls-twilio** [comment]
Camera1Enumerator is an internal class of WebRTC not Android, either way, there has been a lack of response from the customer, so closing.
