### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'tvi.webrtc.CameraSession tvi.webrtc.Camera2Capturer.getCameraSession()' on a null object reference

### ISSUE THREAD

**Issue by Sajjadsaleem411** [twilio/video-quickstart-android#684]
USING updated Lib:
implementation 'com.twilio:video-android:7.0.0'
implementation "com.twilio:audioswitch:1.1.2"

Device: Samsung A10s
Case: It happens when you go background and come again.

Logs:
java.lang.NullPointerException: Attempt to invoke virtual method 'tvi.webrtc.CameraSession tvi.webrtc.Camera2Capturer.getCameraSession()' on a null object reference
        at com.twilio.video.Camera2Capturer.setSession(Camera2Capturer.java:389)
        at com.twilio.video.Camera2Capturer.access$100(Camera2Capturer.java:36)
        at com.twilio.video.Camera2Capturer$1.onFirstFrameAvailable(Camera2Capturer.java:76)
        at tvi.webrtc.CameraCapturer$2.onFrameCaptured(CameraCapturer.java:163)
        at tvi.webrtc.Camera2Session$CaptureSessionCallback.lambda$onConfigured$0$Camera2Session$CaptureSessionCallback(Camera2Session.java:186)
        at tvi.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$fuKynulxmKmczBq4oI32GIjN9pM.onFrame(Unknown Source:2)
        at tvi.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:384)
        at tvi.webrtc.SurfaceTextureHelper.lambda$new$0$SurfaceTextureHelper(SurfaceTextureHelper.java:207)
        at tvi.webrtc.-$$Lambda$SurfaceTextureHelper$WILgr6oZ3ZXfNUC2xvn9STWrdX4.onFrameAvailable(Unknown Source:2)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by afalls-twilio** [comment]
@Sajjadsaleem411  Thank you for the bug report, do you happen to have the model number of the Samsung A10s you are using? (it should be SM-A107F or similar).

**Comment by afalls-twilio** [comment]
@Sajjadsaleem411  This issue has been fixed in an upcoming release.
