### ISSUE TITLE
App crash when trying to connect

### ISSUE THREAD

**Issue by connectedhealthcaremy** [twilio/video-quickstart-android#712]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.twilio.video.quickstart.kotlin, PID: 3407
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.twilio.video.LocalAudioTrack.isReleased()' on a null object reference
        at com.twilio.video.ConnectOptions.checkAudioTracksReleased(ConnectOptions.java:75)
        at com.twilio.video.ConnectOptions$Builder.build(ConnectOptions.java:589)
        at com.twilio.video.ktx.ConnectOptionsKt.createConnectOptions(ConnectOptions.kt:19)
        at com.twilio.video.ktx.Video.connect(Video.kt:85)
        at com.twilio.video.quickstart.kotlin.VideoActivity.connectToRoom(VideoActivity.kt:771)
        at com.twilio.video.quickstart.kotlin.VideoActivity.connectClickListener$lambda-11(VideoActivity.kt:991)
        at com.twilio.video.quickstart.kotlin.VideoActivity.lambda$uiGvu4SB8u86HJ8N3k66TcB5fSo(Unknown Source:0)
        at com.twilio.video.quickstart.kotlin.-$$Lambda$VideoActivity$uiGvu4SB8u86HJ8N3k66TcB5fSo.onClick(Unknown Source:4)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by coycs77** [comment]
Why is this closed with no note as to the root cause or fix?

**Comment by afalls-twilio** [comment]
@ocarevs fixed this issue in a recent commit. (a9a50118e92a7668c2699afc900e76e9f77ff8f8)
