### ISSUE TITLE
RefCountDelegate.java line 42

### ISSUE THREAD

**Issue by keyurmistry316** [twilio/video-quickstart-android#716]
The device crashes when attempting to start a call

Fatal Exception: java.lang.IllegalStateException: release() called on an object with refcount < 1
       at tvi.webrtc.RefCountDelegate.release(RefCountDelegate.java:42)
       at tvi.webrtc.NV21Buffer.release(NV21Buffer.java:53)
       at tvi.webrtc.VideoFrame.release(VideoFrame.java:188)
       at tvi.webrtc.Camera1Session$2.onPreviewFrame(Camera1Session.java:347)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1298)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Device
Brand:Xiaomi
Model:Redmi 5 Plus
Orientation: Portrait
RAM free: 1.12 GB
Disk free: 22.49 GB

Operating System
Version:Android 9
Orientation: Portrait
Rooted:No

**Comment by afalls-twilio** [comment]
@keyurmistry316 can you please retry this with the latest release, 7.3.0? Thanks

**Comment by afalls-twilio** [comment]
No response from customer...
