### ISSUE TITLE
ScreenCapture crashes on Android 14. Reproduced in Twilio example app (exampleScreenCapture)

### ISSUE THREAD

**Issue by Dinalli** [twilio/video-quickstart-android#761]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

App crashes on screen capture on Android 14 (SDK 35) 
When the app rotates capture crashes.

### Steps to Reproduce

Steps to reproduce

Use Android SDK 7.7.1

Update SDK to 35

Update Target SDK to 35.

Load App

Start screen share

Rotate device

App crashes.

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

App should not crash.

#### Actual Behavior

App Crashed

#### Reproduces how Often

100%

#### Logs

FATAL EXCEPTION: CaptureThread
                                                                                                    Process: com.twilio.video.examples.screencapturer, PID: 25137
                                                                                                    java.lang.RuntimeException: java.lang.SecurityException: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
                                                                                                    	at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:156)
                                                                                                    	at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.changeCaptureFormat(ScreenCapturerAndroid.java:181)
                                                                                                    	at com.twilio.video.ScreenCapturer$2.onFrameCaptured(ScreenCapturer.java:97)
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.onFrame(ScreenCapturerAndroid.java:201)
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:370)
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper.lambda$returnTextureFrame$5$tvi-webrtc-SurfaceTextureHelper(SurfaceTextureHelper.java:295)
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.SecurityException: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:2048)
                                                                                                    	at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:759)
                                                                                                    	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1626)
                                                                                                    	at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:268)
                                                                                                    	at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:237)
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.createVirtualDisplay(ScreenCapturerAndroid.java:192)
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.-$$Nest$mcreateVirtualDisplay(Unknown Source:0)
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid$2.run(ScreenCapturerAndroid.java:185)
                                                                                                    	at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
                                                                                                    	at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
                                                                                                    	at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:154)
                                                                                                    	at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196) 
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.changeCaptureFormat(ScreenCapturerAndroid.java:181) 
                                                                                                    	at com.twilio.video.ScreenCapturer$2.onFrameCaptured(ScreenCapturer.java:97) 
                                                                                                    	at tvi.webrtc.ScreenCapturerAndroid.onFrame(ScreenCapturerAndroid.java:201) 
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:370) 
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper.lambda$returnTextureFrame$5$tvi-webrtc-SurfaceTextureHelper(SurfaceTextureHelper.java:295) 
                                                                                                    	at tvi.webrtc.SurfaceTextureHelper$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.isValid(MediaProjectionManagerService.java:1218)
                                                                                                    	at com.android.server.display.DisplayManagerService.createVirtualDisplayInternal(DisplayManagerService.java:1981)
                                                                                                    	at com.android.server.display.DisplayManagerService.-$$Nest$mcreateVirtualDisplayInternal(DisplayManagerService.java:0)
                                                                                                    	at com.android.server.display.DisplayManagerService$BinderService.createVirtualDisplay(DisplayManagerService.java:5297)
                                                                                                    	at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:1002)

### Versions

All relevant version information for issue.

#### Video Android SDK

7.7.1

#### Android API

35

#### Android Device

Galaxy Tab 
Samsung Flip 5

**Comment by Dinalli** [comment]
This still fails.

However as a work around you can use ScreenCaptureAndroid which seems to work.

//        screenCapturer = ScreenCapturer(
//            MainActivity.getContext(),
//            captureResultCode,
//            captureIntent,
//            screenCapturerListener,
//        )
        screenCapturer = ScreenCapturerAndroid(
            captureIntent,
            mediaProjectionCallback
        )

**Comment by afalls-twilio** [comment]
@Dinalli  thanks for the bug report, we actively working on a new WebRTC release which will contain a fix for this issue.

**Comment by afalls-twilio** [comment]
This issue has been fixed with our 7.8.0 release.
