### ISSUE TITLE
Getting Error When i try to get JwtToken

### ISSUE THREAD

**Issue by ananth10** [twilio/video-quickstart-android#77]
I have added  twilio 7.6.0 jar to my project to get jwtToken . but i am getting below error  

 **```
FATAL EXCEPTION: main
                                                                           Process: com.twilio.video.quickstart, PID: 9363
                                                                           java.lang.NoClassDefFoundError: Failed resolution of: Lio/jsonwebtoken/SignatureAlgorithm;
                                                                               at com.twilio.jwt.accesstoken.AccessToken.<init>(AccessToken.java:34)
                                                                               at com.twilio.jwt.accesstoken.AccessToken.<init>(AccessToken.java:23)
                                                                               at com.twilio.jwt.accesstoken.AccessToken$Builder.build(AccessToken.java:137)
                                                                               at com.twilio.video.quickstart.activity.VideoActivity.getToken(VideoActivity.java:190)
                                                                               at com.twilio.video.quickstart.activity.VideoActivity.onCreate(VideoActivity.java:111)
                                                                               at android.app.Activity.performCreate(Activity.java:6876)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "io.jsonwebtoken.SignatureAlgorithm" on path: DexPathList[[zip file "/data/app/com.twilio.video.quickstart-2/base.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.twilio.video.quickstart-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.twilio.video.quickstart-2/lib/arm64, /data/app/com.twilio.video.quickstart-2/base.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.twilio.video.quickstart-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at com.twilio.jwt.accesstoken.AccessToken.<init>(AccessToken.java:34) 
                                                                               at com.twilio.jwt.accesstoken.AccessToken.<init>(AccessToken.java:23) 
                                                                               at com.twilio.jwt.accesstoken.AccessToken$Builder.build(AccessToken.java:137) 
                                                                               at com.twilio.video.quickstart.activity.VideoActivity.getToken(VideoActivity.java:190) 
                                                                               at com.twilio.video.quickstart.activity.VideoActivity.onCreate(VideoActivity.java:111) 
                                                                               at android.app.Activity.performCreate(Activity.java:6876) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:158) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                           	Suppressed: java.lang.ClassNotFoundException: io.jsonwebtoken.SignatureAlgorithm
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 18 more
                                                                            Caused by: java.lang.NoClassDefFoundEr
```**

**Comment by aaalaniz** [comment]
Hey @ananth10 

It appears you are missing the [Java JWT](https://github.com/jwtk/jjwt) library from the Twilio Java jar. If you want to use the Twilio Java Library jar directly then you will need the [jar-with-dependencies](http://search.maven.org/remotecontent?filepath=com/twilio/sdk/twilio-java-sdk/6.3.0/twilio-java-sdk-6.3.0-jar-with-dependencies.jar). However, I recommend using Gradle to pull in the Twilio Java Library for an Android project (see snippet below).

Include Twilio Java Library in Gradle

```
dependencies {
    compile 'com.twilio.sdk:twilio-java-sdk:6.3.0'
}
```

**Comment by ananth10** [comment]
@aaalaniz . Thank you.

**Comment by ananth10** [comment]
@aaalaniz i have tried to use this   **compile 'com.twilio.sdk:twilio-java-sdk:6.3.0'** version. but in this library i could not fine VideoGrant class.  so can you tell me in  which version you have implemented **"VideoGrant**" api ?

**Comment by ujwalrajeev** [comment]
Please help me I am trying to create a video conference app using Twilio but I am facing problems now 

final VideoGrant grant = new VideoGrant();
grant.setRoom(groupName);

Here setRoom cannot be resolved and also

final String jwt = token.toJWT();

toJWT cannot be resolved

I have imported these,
import com.twilio.jwt.accesstoken.AccessToken;
import com.twilio.jwt.accesstoken.VideoGrant;


and gradle includes these,
implementation 'com.twilio:video-android:5.8.0'
implementation 'com.twilio.sdk:twilio-java-sdk:6.3.0'
implementation 'com.twilio.sdk:twilio:7.0.0'

Please help. @aaalaniz @Meshsoft
