### ISSUE TITLE
Twilio SDK 1.0.0-beta15: Exception when trying to start quickstart app  in Emulator

### ISSUE THREAD

**Issue by FranziscaZarrai** [twilio/video-quickstart-android#92]
When trying to start the most recent version of the quickstart app in an emulator (it uses the twilio SDK version com.twilio:video-android:1.0.0-beta15)  it fails with an exception. The emulator specification is as follows:

Name: Nexus_5_API_25
CPU/ABI: Google APIs Intel Atom (x86_64)
Target: google_apis [Google APIs] (API level 25)
Skin: nexus_5
SD Card: 100M
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5
vm.heapSize: 64
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 25
hw.audioInput: yes
image.sysdir.1: system-images/android-25/google_apis/x86_64/
tag.id: google_apis
showDeviceFrame: yes
hw.camera.back: emulated
hw.mainKeys: no
AvdId: Nexus_5_API_25
hw.camera.front: emulated
hw.lcd.density: 480
avd.ini.displayname: Nexus 5 API 25
hw.gpu.mode: auto
hw.device.hash2: MD5:2fa0e16c8cceb7d385183284107c0c88
hw.ramSize: 1536
hw.trackBall: no
hw.battery: yes
hw.cpu.ncore: 4
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 1500M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

And here is the exception:

```
04-01 01:13:09.319 1289-1289/? E/CameraService: CameraService::connect X (PID 12208) rejected (invalid camera ID -1)
04-01 01:13:09.320 12208-12208/com.twilio.video.quickstart E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.twilio.video.quickstart, PID: 12208
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twilio.video.quickstart/com.twilio.video.quickstart.activity.VideoActivity}: java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                              Caused by: java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
                                                                                 at com.twilio.video.LocalMedia.checkSupportedFormats(LocalMedia.java:349)
                                                                                 at com.twilio.video.LocalMedia.addVideoTrack(LocalMedia.java:169)
                                                                                 at com.twilio.video.LocalMedia.addVideoTrack(LocalMedia.java:146)
                                                                                 at com.twilio.video.quickstart.activity.VideoActivity.createLocalMedia(VideoActivity.java:235)
                                                                                 at com.twilio.video.quickstart.activity.VideoActivity.onCreate(VideoActivity.java:123)
                                                                                 at android.app.Activity.performCreate(Activity.java:6679)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
04-01 01:13:09.513 1687-5475/system_process E/EGL_emulation: tid 5475: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
04-01 01:13:09.910 2502-12139/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 225, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
04-01 01:13:09.911 2502-12139/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
04-01 01:13:09.911 2502-12139/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
04-01 01:13:09.911 2502-12139/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
```

I used the emulator before with previous twilio SDK versions and it did work correctly - i.e. it was showing a cube moving around the screen (emulated camera).

**Comment by aaalaniz** [comment]
Hey @FranziscaZarrai 

Thanks for reporting this. I will root cause this asap.

**Comment by aaalaniz** [comment]
Hey @FranziscaZarrai 

I am unable to reproduce this crash. After investigating your log further, there appears to be an error connecting to the emulator CameraService. 

```
04-01 01:13:09.319 1289-1289/? E/CameraService: CameraService::connect X (PID 12208) rejected (invalid camera ID -1)
```

I've attached the [Nexus 5 Emulator setup](https://github.com/twilio/video-quickstart-android/files/891445/my-n5-emu.txt) I used to try and recreate this crash. The only property I was not able to match from your emulator configuration was the number of cores. I can only set 1 or 2 cores and you selected 4 cores. 

Can you try using 2 cores for your emulator and see if the crash persists? 

Thanks!

**Comment by FranziscaZarrai** [comment]
@aaalaniz Thank you for investigating, i'll try it with a different emulator setup as you suggested and will update this ticket accordingly.

**Comment by aaalaniz** [comment]
Hey @FranziscaZarrai 

Were you able to use the Nexus 5 emulator with my suggestions?

Thanks!

**Comment by FranziscaZarrai** [comment]
@aaalaniz Apologies for the delay - I'll give this a try today

**Comment by kesh-1139** [comment]
I am getting the same error when creating VideoTrak. I am using twilio-video 1.0.1. Can you please let me know what is going wrong?
